import 'package:get_it/get_it.dart';
import 'package:sky_high/core/services/storage_service.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  final StorageService _storage = GetIt.I<StorageService>();

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'search_hint': 'Search courses...',
      'categories': 'Categories',
      'continue_studying': 'Continue Studying',
      'free_exams': 'Free Exams',
      'study_materials': 'Study Materials',
      'view_all': 'View All',
      'login': 'Login',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'premium_status': 'Premium Status',
      'about_us': 'About Us',
      'write_review': 'Write a Review',
      'contact_whatsapp': 'Contact on WhatsApp',
      'no_recent_study': 'Start a course to see your progress here',
      'start_learning': 'Start Learning',
      'all_categories': 'All Categories',
      'explore_courses': 'Explore our wide range of courses',
      'notification': 'Notification',
      'privacy': 'Privacy',
      'purchased': 'Purchased',
      'achieved': 'Achieved',
      'certificates': 'Certificates',
      'about_desc': "India's leading learning platform for government exams.",
      'whatsapp_title': 'Join Community',
    },
    'Tamil': {
      'search_hint': 'பாடங்களைத் தேடுங்கள்...',
      'categories': 'வகைகள்',
      'continue_studying': 'தொடர்ந்து படிக்கவும்',
      'free_exams': 'இலவச தேர்வுகள்',
      'study_materials': 'பாடப் பொருட்கள்',
      'view_all': 'அனைத்தையும் பார்',
      'login': 'உள்நுழைய',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'edit_profile': 'சுயவிவரத்தைத் திருத்து',
      'premium_status': 'பிரீமியம் நிலை',
      'about_us': 'எங்களைப் பற்றி',
      'write_review': 'மதிப்புரை எழுதுங்கள்',
      'contact_whatsapp': 'வாட்ஸ்அப்பில் தொடர்பு கொள்ளவும்',
      'no_recent_study': 'உங்கள் முன்னேற்றத்தைக் காண ஒரு பாடத்தைத் தொடங்குங்கள்',
      'start_learning': 'படிக்கத் தொடங்குங்கள்',
      'all_categories': 'அனைத்து வகைகள்',
      'explore_courses': 'எங்கள் பரந்த அளவிலான பாடங்களை ஆராயுங்கள்',
      'notification': 'அறிவிப்பு',
      'privacy': 'தனியுரிமை',
      'purchased': 'வாங்கப்பட்டது',
      'achieved': 'சாதிக்கப்பட்டது',
      'certificates': 'சான்றிதழ்கள்',
      'about_desc': 'இந்தியாவின் முன்னணி அரசுத் தேர்வுப் பயிற்சி தளம்.',
      'whatsapp_title': 'சமூகத்தில் இணையுங்கள்',
    },
    'Telugu': {
      'search_hint': 'కోర్సుల కోసం వెతకండి...',
      'categories': 'వర్గాలు',
      'continue_studying': 'చదువు కొనసాగించండి',
      'free_exams': 'ఉచిత పరీక్షలు',
      'study_materials': 'అధ్యయన సామాగ్రి',
      'view_all': 'అన్నీ చూడండి',
      'login': 'లాగిన్',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగులు',
      'logout': 'లాగ్ అవుట్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'premium_status': 'ప్రీమియం స్థితి',
      'about_us': 'మా గురించి',
      'write_review': 'సమీక్ష రాయండి',
      'contact_whatsapp': 'వాట్సాప్‌లో సంప్రదించండి',
      'no_recent_study': 'మీ పురోగతిని చూడటానికి ఒక కోర్సును ప్రారంభించండి',
      'start_learning': 'చదువు ప్రారంభించండి',
      'all_categories': 'అన్ని వర్గాలు',
      'explore_courses': 'మా విస్తృత కోర్సులను అన్వేషించండి',
      'notification': 'నోటిఫಿಕేషన్',
      'privacy': 'గోప్యత',
      'purchased': 'కొనుగోలు చేయబడింది',
      'achieved': 'సాధించినవి',
      'certificates': 'సర్టిఫికెట్లు',
      'about_desc': 'ప్రభుత్వ పరీక్షల కోసం భారతదేశపు ప్రముఖ లెర్నింగ్ ప్లాట్‌ఫారమ్.',
      'whatsapp_title': 'కమ్యూనిటీలో చేరండి',
    },
    'Hindi': {
      'search_hint': 'कोर्स खोजें...',
      'categories': 'श्रेणियाँ',
      'continue_studying': 'पढ़ाई जारी रखें',
      'free_exams': 'मुफ्त परीक्षा',
      'study_materials': 'अध्ययन सामग्री',
      'view_all': 'सभी देखें',
      'login': 'लॉगिन',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'premium_status': 'प्रीमियम स्थिति',
      'about_us': 'हमारे बारे में',
      'write_review': 'समीक्षा लिखें',
      'contact_whatsapp': 'व्हाट्सएप पर संपर्क करें',
      'no_recent_study': 'अपनी प्रगति देखने के लिए एक कोर्स शुरू करें',
      'start_learning': 'पढ़ना शुरू करें',
      'all_categories': 'सभी श्रेणियाँ',
      'explore_courses': 'हमारे पाठ्यक्रमों की विस्तृत श्रृंखला देखें',
      'notification': 'अधिसूचना',
      'privacy': 'गोपनीयता',
      'purchased': 'खरीदा गया',
      'achieved': 'हासिल किया',
      'certificates': 'प्रमाण पत्र',
      'about_desc': 'सरकारी परीक्षाओं के लिए भारत का अग्रणी शिक्षण मंच।',
      'whatsapp_title': 'समुदाय से जुड़ें',
    },
    'Malayalam': {
      'search_hint': 'കോഴ്സുകൾ തിരയുക...',
      'categories': 'വിഭാഗങ്ങൾ',
      'continue_studying': 'പഠനം തുടരുക',
      'free_exams': 'സൗജന്യ പരീക്ഷകൾ',
      'study_materials': 'പഠന സാമഗ്രികൾ',
      'view_all': 'എല്ലാം കാണുക',
      'login': 'ലോഗിൻ',
      'profile': 'പ്രൊഫൈൽ',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'logout': 'ലോഗ് ഔട്ട്',
      'edit_profile': 'പ്രൊഫൈൽ തിരുത്തുക',
      'premium_status': 'പ്രീಮിയം സ്റ്റാറ്റസ്',
      'about_us': 'ഞങ്ങളെക്കുറിച്ച്',
      'write_review': 'അഭിപ്രായം എഴുതുക',
      'contact_whatsapp': 'വാട്ട്‌സ്ആപ്പിൽ ബന്ധപ്പെടുക',
      'no_recent_study': 'നിങ്ങളുടെ പുരോഗതി കാണാൻ ഒരു കോഴ്സ് തുടങ്ങുക',
      'start_learning': 'പഠനം തുടങ്ങുക',
      'all_categories': 'എല്ലാ വിഭാഗങ്ങളും',
      'explore_courses': 'ഞങ്ങളുടെ കോഴ്സുകൾ പര്യവേക്ഷണം ചെയ്യുക',
      'notification': 'അറിയിപ്പ്',
      'privacy': 'സ്വകാര്യത',
      'purchased': 'വാങ്ങിയവ',
      'achieved': 'നേടിയവ',
      'certificates': 'സർട്ടിഫിക്കറ്റുകൾ',
      'about_desc': 'സർക്കാർ പരീക്ഷകൾക്കായുള്ള ഇന്ത്യയിലെ പ്രമുഖ പഠന പ്ലാറ്റ്‌ഫോം.',
      'whatsapp_title': 'കമ്മ്യൂണിറ്റിയിൽ ചേരുക',
    },
    'Kannada': {
      'search_hint': 'ಕೋರ್ಸ್‌ಗಳಿಗಾಗಿ ಹುಡುಕಿ...',
      'categories': 'ವರ್ಗಗಳು',
      'continue_studying': 'ಓದುವುದನ್ನು ಮುಂದುವರಿಸಿ',
      'free_exams': 'ಉಚಿತ ಪರೀಕ್ಷೆಗಳು',
      'study_materials': 'ಅಧ್ಯಯನ ಸಾಮಗ್ರಿಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'login': 'ಲಾಗಿನ್',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'logout': 'ಲೋಗ್ ಔಟ್',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
      'premium_status': 'ಪ್ರೀಮಿಯಂ ಸ್ಥಿತಿ',
      'about_us': 'ನಮ್ಮ ಬಗ್ಗೆ',
      'write_review': 'ವಿಮರ್ಶೆ ಬರೆಯಿರಿ',
      'contact_whatsapp': 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ',
      'no_recent_study': 'ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ನೋಡಲು ಕೋರ್ಸ್ ಪ್ರಾರಂಭಿಸಿ',
      'start_learning': 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ',
      'all_categories': 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
      'explore_courses': 'ನಮ್ಮ ಕೋರ್ಸ್‌ಗಳ ಶ್ರೇಣಿಯನ್ನು ಅನ್ವೇಷಿಸಿ',
      'notification': 'ಅಧಿಸೂಚನೆ',
      'privacy': 'ಗೌಪ್ಯತೆ',
      'purchased': 'ಖರೀದಿಸಲಾಗಿದೆ',
      'achieved': 'ಸಾಧಿಸಲಾಗಿದೆ',
      'certificates': 'ಪ್ರಮಾಣಪತ್ರಗಳು',
      'about_desc': 'ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆಗಳಿಗಾಗಿ ಭಾರತದ ಪ್ರಮುಖ ಕಲಿಕಾ ವೇದಿಕೆ.',
      'whatsapp_title': 'ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
    },
  };

  String tr(String key) {
    final language = _storage.getSelectedLanguage();
    return _translations[language]?[key] ??
        _translations['English']?[key] ??
        key;
  }
}
