import 'package:get_it/get_it.dart';
import 'package:sky_high/core/services/storage_service.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();
  final StorageService _storage = GetIt.I<StorageService>();

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'free_study_materials': 'Free Study Materials',
      'search_hint': 'Search courses, tests, subjects...',
      'categories': 'Categories',
      'continue_studying': 'Continue Studying',
      'free_exams': 'Free Exams',
      'study_materials': 'Study Materials',
      'view_all': 'View All',
      'login': 'Login',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'premium_status': 'Premium Status',
      'about_us': 'About Us',
      'write_review': 'Write a Review',
      'contact_whatsapp': 'Contact on WhatsApp',
      'no_recent_study': 'Start a course to see your progress here',
      'start_learning': 'Start Learning',
      'all_categories': 'All Categories',
      'explore_courses': 'Explore our wide range of courses',
      'notification': 'Notification',
      'privacy': 'Privacy',
      'purchased': 'Purchased',
      'achieved': 'Achieved',
      'certificates': 'Certificates',
      'about_desc': "India's leading learning platform for government exams.",
      'whatsapp_title': 'Join Community',
      'my_courses': 'My Courses',
      'leaderboard': 'Leaderboard',
      'mock_tests': 'Mock Tests',
      'continue_learning': 'Continue learning',
      'practice_improve': 'Practice & improve',
      'compete_achieve': 'Compete & achieve',
      'welcome_msg': 'Welcome to Sky High',
      'login_track': 'Login to track your progress',
      'hi': 'Hi',
      'continue_journey': "Let's continue your learning journey!",
      'identity_required': 'Identity Required',
      'signin_sync':
          'Sign in to sync your progress, access premium certificates, and join the elite community.',
      'signin_now': 'SIGN IN NOW',
      'logout_confirm': 'Are you sure you want to log out?',
      'close': 'Close',
      'cancel': 'Cancel',
      'email': 'Email',
      'call': 'Call',
      'address': 'Address',
      'whatsapp_community': 'Join WhatsApp Community',
      'connect_aspirants': 'Connect with 50,000+ Aspirants',
      'happy_students': 'Our Happy Students',
      'what_students_say': 'What Our Students Say',
      'login_required': 'Login Required',
      'signin_payment': 'Please sign in to proceed with your\npayment.',
      'search_categories': 'Search categories...',
      'no_categories_found': 'No categories found',
      'try_searching_else': 'Try searching for something else',
      'explore_exam_categories': 'Explore government exam categories',
      'find_category_prep': 'Find the right category for your exam preparation',
      'no_materials_available': 'No Materials available',
      'no_companies_available': 'No Companies available',
      'check_back_later': 'Check back later for new content in this category.',
      'cant_find_looking': "Can't find what you're looking for?",
      'help_find_category': 'Let us help you find the right category.',
      'contact_us': 'Contact Us',
      'organization': 'Organization',
      'item': 'Item',
      'companies': 'Companies',
      'search_books_notes': 'Search for books, notes...',
      'learning_hub_title': 'Your Learning Hub',
      'learning_hub_desc':
          'Access all your study modules, mock tests, and video lessons from the side menu.',
      'tap_menu_switch': 'Tap the menu icon to switch modules',
      'track_progress_section': 'Track your progress in each section',
      'got_it_lets_go': "Got it, Let's Go!",
      'modules': 'Modules',
      'your_progress': 'Your Progress',
      'keep_learning_great': "Keep learning, you're doing great!",
      'about_organisation': 'About Organisation',
      'top_opportunities': 'Top Opportunities',
      'no_opportunities_yet': 'No Opportunities Yet',
      'check_back_soon_openings': 'Check back soon for new openings.',
      'browse_materials': 'Browse Materials',
      'quick_access': 'Quick Access',
      'exit_learning_journey': 'Exit Learning Journey?',
      'exit_confirm_msg':
          'Your progress for this session will be saved. Are you sure you want to exit?',
      'keep_learning_btn': 'Keep Learning',
      'yes_exit': 'Yes, Exit',
      'complete_next_module': 'Complete & Next Module',
      'build_career_serve': 'Build your career. Serve the nation.',
      'worldwide': 'Worldwide',
      'openings': 'Openings',
      'trending': 'Trending',
      'learning_journey': 'LEARNING JOURNEY',
      'mod_basic_info': 'Basic Information',
      'mod_syllabus': 'Syllabus',
      'mod_prep_plan': 'Preparation Plan',
      'mod_notes': 'Chapter-wise / Topic-wise Notes',
      'mod_pyq': 'Chapter-wise / Topic-wise Previous Year Questions',
      'mod_mcq': 'Chapter-wise / Topic-wise MCQ',
      'mod_video_lessons': 'Chapter-wise / Topic-wise Video Lessons',
      'mod_test_series': 'Online Test Series',
      'finish_journey': 'Finish Journey',
      'all_modules_completed':
          'Congratulations! You have completed all modules! 🎉',
      'search_opportunities': 'Search opportunities...',
      'openings_count': 'Openings',
      'resume': 'Resume',
      'last_studied_yesterday': 'Last studied: Yesterday',
      'sub_posts': 'Sub-posts',
      // 'mock_tests': 'Mock Tests',
      'study_material': 'Study Material',
      'previous_year': 'Previous Year',
      'syllabus': 'Syllabus',
      'got_it': 'Got it',
      'start': 'Start',
      //'continue_learning': 'Continue Learning',
      'government_org': 'Government Organization',
      'explore_categories': 'Explore top government exam categories',
      'continue_learning_sub': 'Continue\nlearning',
      'notes_pdfs_sub': 'Notes, PDFs\n& more',
      'module_prefix': 'MOD',
      'content_locked_upgrade': 'This content is locked. Upgrade to unlock.',
      'premium_content': 'Premium Content',
      'premium_module_desc':
          'This module is part of our Elite Learning Path. Upgrade your subscription to unlock all modules and advanced test series.',
      'maybe_later': 'Maybe Later',
      'upgrade_now': 'Upgrade Now',
      'login_module_desc':
          'Please login to access premium modules and track your progress.',
      'login_now': 'Login Now',
      'no_courses_available': 'No Courses Available',
      'check_back_later_courses':
          'Currently, there are no courses available for your selected preferences. Please check back later!',

      'failed_load_materials': 'Failed to load materials',
      'no_matching_found': 'No matching materials found',
      'video_player_coming_soon': 'Video player coming soon!',
      'failed_load_jobs': 'Failed to load jobs',
      'resume_course': 'Resume Course',
      'company_default_desc':
          'One of the world\'s largest railway networks, connecting 7,000+ stations across India — a pillar of national infrastructure and public service excellence.',
      'no_files_available_desc':
          'There are no files available for this section at this moment. We are working hard to bring them to you soon!',
      'no_rankings_yet': 'No Rankings Yet!',
      'leaderboard_empty_desc':
          'The leaderboard is empty for now.\nStart learning and be the first to make it here!',
      'climb_leaderboard': 'Climb the leaderboard',
      'study_learn_title': 'Study & Learn',
      'study_learn_desc': 'Complete modules and expand your knowledge',
      'take_tests_title': 'Take Tests',
      'take_tests_desc': 'Attempt tests and improve your score',
      'earn_points_title': 'Earn Points',
      'earn_points_desc': 'Score higher and climb the ranks',
      'consistency_today': 'Be consistent today,',
      'lead_tomorrow': 'Lead the leaderboard tomorrow!',
      'tagline': 'Reach for the stars',
      'skip': 'Skip',
      'get_started': 'Get Started',
      'next_step': 'Next Step',
      'onboarding_title_1': 'Success is\nEasy to Achieve',
      'onboarding_desc_1':
          'Unlock your potential with our personalized learning ecosystem designed for excellence.',
      'onboarding_highlight_1': 'Learn smarter, not harder',
      'onboarding_title_2': 'Master Your\nUpcoming Exams',
      'onboarding_desc_2':
          'Dive into a vast library of mock tests and real-time performance analytics.',
      'onboarding_highlight_2': 'Excellence in every test',
      'onboarding_title_3': 'Structured\nLearning Paths',
      'onboarding_desc_3':
          'Explore category-based study modules tailored to your specific academic needs.',
      'onboarding_highlight_3': 'Category based study',
      'no_active_notifications': 'No Active Notifications',

      'access_premium_journey': 'Access your premium learning journey',
      'otp_login': 'OTP LOGIN',
      'password_tab': 'PASSWORD',
      'email_address': 'Email Address',
      'otp_hint': '6-digit OTP Code',
      'resend_otp_in': 'Resend OTP in',
      'resend_otp': 'Resend OTP',
      'password_hint': 'Password',
      'activate_session': 'ACTIVATE SESSION',
      'get_otp_code': 'GET OTP CODE',
      'sign_in': 'SIGN IN',
      'dont_have_account': "Don't have an account? ",
      'create_profile': 'Create Profile',
      'enter_email': 'Please enter your email',
      'enter_password': 'Please enter your password',
      'otp_sent_success': 'OTP sent to your email',
      'otp_send_failed': 'Failed to send OTP. Please check your email.',
      'enter_otp': 'Please enter the OTP',
      'invalid_otp_failed': 'Invalid OTP or login failed',
      'invalid_credentials': 'Invalid email or password',
      'about_exam': 'About the Exam',
      'syllabus_overview': 'Syllabus Overview',
      'target_year': 'Target Year',
      'duration': 'Duration',
      'questions': 'Questions',
      'rating': 'Rating',
      'start_preparation': 'Start Preparation',
      'submit_test_title': 'Submit Test?',
      'submit_test_desc': 'Are you sure you want to submit your test?',
      'unanswered_questions_warning': 'You have {count} unanswered questions.',
      'review_more': 'Review More',
      'submit_now': 'Submit Now',
      'quit_test_title': 'Quit Test?',
      'quit_test_desc':
          'Are you sure you want to exit? Your current test progress will be lost and cannot be recovered.',
      'stay': 'Stay',
      'exit': 'Exit',
      'back_to_learning': 'Back to Learning',
      'no_questions_found': 'No Questions Found',
      'no_questions_desc':
          'We couldn\'t find any questions for this test set at the moment. Please check back later.',
      'go_back': 'GO BACK',
      'test_instructions': 'Test Instructions',
      'submitting_test': 'Submitting your test...',
      'important_rules': 'IMPORTANT RULES',
      'rule_1': 'Each question carries 1 mark.',
      'rule_2': 'Total duration is {min} minutes.',
      'rule_3': 'The test will auto-submit when time is up.',
      'rule_4': 'Questions are available in English.',
      'start_test_now': 'START TEST NOW',
      'minutes': 'Minutes',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'progress': 'Progress',
      'continue_lesson': 'Continue lesson',
      'explore_gov_exams': 'Explore top government exam categories',
      'no_courses_right_now': 'No courses available right now',
      'available_materials': 'Available Materials',
      'items_count': '{count} items',
      'mod_prefix': 'MOD',
      'no_test_series': 'No test series available yet.',
      'no_sets_available': 'No sets available for this module yet.',
      'module_integrated_soon':
          'This module is currently being integrated.\nPlease check back soon.',
      // 'learning_journey': 'LEARNING JOURNEY',
      // 'modules': 'Modules',
      // 'your_progress': 'Your Progress',
      // 'keep_learning_great': 'Keep learning! You\'re doing great.',
      // 'all_modules_completed': 'All modules in this course completed!',
      // 'finish_journey': 'FINISH JOURNEY',
      // 'complete_next_module': 'COMPLETE & NEXT MODULE',
      'exit_confirm_title': 'Exit Journey?',
      'exit_confirm_desc':
          'Are you sure you want to exit? Your progress in this session will be saved.',
      'dismiss_all': 'Dismiss All',
      'instruction_guide_title': 'Quick Instruction Guide',
      'instruction_guide_desc':
          'Access all your study modules, mock tests, and video lessons from the side menu.',
      'instruction_step_1': 'Tap the menu icon to switch modules',
      'instruction_step_2': 'Track your progress in each section',
      // 'got_it_lets_go': 'Got it, Let\'s Go!',
      // 'keep_learning_btn': 'Keep Learning',
      // 'yes_exit': 'Yes, Exit',
      'discover_learning_paths': 'Discover the best learning paths',
      'smart_prep_future': 'Smart preparation for your bright future',
      'join_community': 'Join Community',
      // 'connect_aspirants': 'Connect with 50,000+ Aspirants',
      'join_whatsapp': 'Join WhatsApp Community',
      'about_platform_desc':
          'India\'s leading learning platform for government exams.',
      'copyright_text': '© 2026 SkyHigh Learning. All rights reserved.',
      // 'email': 'Email',
      // 'call': 'Call',
      // 'address': 'Address',
      'facebook': 'Facebook',
      'cat_business': 'Business',
      'cat_marketing': 'Marketing',
      'cat_design': 'Design',
      'no_internet': 'No Connection',
      'connect_internet': 'Connect Internet',
      'connect_internet_desc':
          'Please check your internet connection and try again.',
      'try_again': 'Try Again',
      'checking_connection': 'Checking...',
    },
    'Tamil': {
      'free_study_materials': 'இலவச பாடப் பொருட்கள்',
      'search_hint': 'பாடங்கள், தேர்வுகள், பாடங்களைத் தேடுங்கள்...',
      'categories': 'வகைகள்',
      'continue_studying': 'தொடர்ந்து படிக்கவும்',
      'free_exams': 'இலவச தேர்வுகள்',
      'study_materials': 'பாடப் பொருட்கள்',
      'view_all': 'அனைத்தையும் பார்',
      'login': 'உள்நுழைய',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'edit_profile': 'சுயவிவரத்தைத் திருத்து',
      'premium_status': 'பிரீமியம் நிலை',
      'about_us': 'எங்களைப் பற்றி',
      'write_review': 'மதிப்புரை எழுதுங்கள்',
      'contact_whatsapp': 'வாட்ஸ்அப்பில் தொடர்பு கொள்ளவும்',
      'no_recent_study':
          'உங்கள் முன்னேற்றத்தைக் காண ஒரு பாடத்தைத் தொடங்குங்கள்',
      'start_learning': 'படிக்கத் தொடங்குங்கள்',
      'all_categories': 'அனைத்து வகைகள்',
      'explore_courses': 'எங்கள் பரந்த அளவிலான பாடங்களை ஆராயுங்கள்',
      'notification': 'அறிவிப்பு',
      'privacy': 'தனியுரிமை',
      'purchased': 'வாங்கப்பட்டது',
      'achieved': 'சாதிக்கப்பட்டது',
      'certificates': 'சான்றிதழ்கள்',
      'about_desc': 'இந்தியாவின் முன்னணி அரசுத் தேர்வுப் பயிற்சி தளம்.',
      'whatsapp_title': 'சமூகத்தில் இணையுங்கள்',
      'my_courses': 'எனது பாடங்கள்',
      'leaderboard': 'முன்னணி வரிசை',
      'mock_tests': 'மாதிரி தேர்வுகள்',
      'continue_learning': 'தொடர்ந்து கற்கவும்',
      'practice_improve': 'பயிற்சி மற்றும் மேம்பாடு',
      'compete_achieve': 'போட்டியிட்டு சாதிக்கவும்',
      'welcome_msg': 'ஸ்கை ஹை-க்கு வரவேற்கிறோம்',
      'login_track': 'உங்கள் முன்னேற்றத்தைக் கண்காணிக்க உள்நுழையவும்',
      'hi': 'வணக்கம்',
      'continue_journey': 'உங்கள் கற்றல் பயணத்தைத் தொடர்வோம்!',
      'identity_required': 'அடையாளம் தேவை',
      'signin_sync':
          'உங்கள் முன்னேற்றத்தை ஒத்திசைக்கவும், பிரீமியம் சான்றிதழ்களை அணுகவும் மற்றும் உயரடுக்கு சமூகத்தில் சேரவும் உள்நுழையவும்.',
      'signin_now': 'இப்போது உள்நுழைக',
      'logout_confirm': 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'close': 'மூடு',
      'cancel': 'ரத்து செய்',
      'email': 'மின்னஞ்சல்',
      'call': 'அழைப்பு',
      'address': 'முகவரி',
      'whatsapp_community': 'வாட்ஸ்அப் சமூகத்தில் இணையுங்கள்',
      'connect_aspirants': '50,000+ தேர்வர்களுடன் இணையுங்கள்',
      'happy_students': 'எங்கள் மகிழ்ச்சியான மாணவர்கள்',
      'what_students_say': 'எங்கள் மாணவர்கள் என்ன சொல்கிறார்கள்',
      'login_required': 'உள்நுழைவு தேவை',
      'signin_payment': 'உங்கள் கட்டணத்தைத் தொடர உள்நுழையவும்.',
      'search_categories': 'வகைகளைத் தேடுங்கள்...',
      'no_categories_found': 'வகைகள் எதுவும் காணப்படவில்லை',
      'try_searching_else': 'வேறு ஏதாவது தேட முயற்சிக்கவும்',
      'explore_exam_categories': 'அரசுத் தேர்வு வகைகளை ஆராயுங்கள்',
      'find_category_prep':
          'உங்கள் தேர்வுத் தயாரிப்பிற்கான சரியான வகையைக் கண்டறியவும்',
      'no_materials_available': 'பாடப் பொருட்கள் எதுவும் இல்லை',
      'no_companies_available': 'நிறுவனங்கள் எதுவும் இல்லை',
      'check_back_later':
          'இந்தப் பிரிவில் புதிய உள்ளடக்கத்திற்குப் பிறகு பார்க்கவும்.',
      'cant_find_looking': 'நீங்கள் தேடுவதைக் கண்டுபிடிக்க முடியவில்லையா?',
      'help_find_category':
          'சரியான வகையைக் கண்டறிய நாங்கள் உங்களுக்கு உதவுகிறோம்.',
      'contact_us': 'எங்களைத் தொடர்பு கொள்ளவும்',
      'organization': 'நிறுவனம்',
      'item': 'பொருள்',
      'companies': 'நிறுவனங்கள்',
      'search_books_notes': 'புத்தகங்கள், குறிப்புகளைத் தேடுங்கள்...',
      'learning_hub_title': 'உங்கள் கற்றல் மையம்',
      'learning_hub_desc':
          'உங்கள் பாடப் பிரிவுகள், மாதிரித் தேர்வுகள் மற்றும் வீடியோ பாடங்களை பக்க மெனுவிலிருந்து அணுகவும்.',
      'tap_menu_switch': 'பாடப் பிரிவுகளை மாற்ற மெனு ஐகானைத் தட்டவும்',
      'track_progress_section':
          'ஒவ்வொரு பகுதியிலும் உங்கள் முன்னேற்றத்தைக் கண்காணிக்கவும்',
      'got_it_lets_go': 'சரி, தொடங்குவோம்!',
      'modules': 'பாடப் பிரிவுகள்',
      'your_progress': 'உங்கள் முன்னேற்றம்',
      'keep_learning_great':
          'தொடர்ந்து படியுங்கள், நீங்கள் சிறப்பாகச் செய்கிறீர்கள்!',
      'about_organisation': 'நிறுவனத்தைப் பற்றி',
      'top_opportunities': 'சிறந்த வாய்ப்புகள்',
      'no_opportunities_yet': 'இன்னும் வாய்ப்புகள் இல்லை',
      'check_back_soon_openings':
          'புதிய வாய்ப்புகளுக்கு விரைவில் மீண்டும் சரிபார்க்கவும்.',
      'browse_materials': 'பாடப் பொருட்களைப் பார்க்கவும்',
      'quick_access': 'விரைவு அணுகல்',
      'exit_learning_journey': 'கற்றல் பயணத்திலிருந்து வெளியேறவா?',
      'exit_confirm_msg':
          'இந்த அமர்வுக்கான உங்கள் முன்னேற்றம் சேமிக்கப்படும். நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'keep_learning_btn': 'தொடர்ந்து கற்கவும்',
      'yes_exit': 'ஆம், வெளியேறு',
      'complete_next_module': 'முடித்து அடுத்த பாடத்திற்குச் செல்லவும்',
      'build_career_serve':
          'உங்கள் வாழ்க்கையை உருவாக்குங்கள். தேசத்திற்கு சேவை செய்யுங்கள்.',
      'worldwide': 'உலகளாவிய',
      'openings': 'வாய்ப்புகள்',
      'trending': 'பிரபலமானவை',
      'learning_journey': 'கற்றல் பயணம்',
      'mod_basic_info': 'அடிப்படை தகவல்',
      'mod_syllabus': 'பாடத்திட்டம்',
      'mod_prep_plan': 'தயாரிப்பு திட்டம்',
      'mod_notes': 'பாடம் வாரியான / தலைப்பு வாரியான குறிப்புகள்',
      'mod_pyq': 'பாடம் வாரியான / தலைப்பு வாரியான முந்தைய ஆண்டு வினாக்கள்',
      'mod_mcq': 'பாடம் வாரியான / தலைப்பு வாரியான பலமுறை வினாக்கள்',
      'mod_video_lessons': 'பாடம் வாரியான / தலைப்பு வாரியான வீடியோ பாடங்கள்',
      'mod_test_series': 'ஆன்லைன் தேர்வுத் தொடர்',
      'finish_journey': 'பயணத்தை முடிக்கவும்',
      'all_modules_completed':
          'வாழ்த்துகள்! நீங்கள் அனைத்து பாடங்களையும் முடித்துவிட்டீர்கள்! 🎉',
      'search_opportunities': 'வாய்ப்புகளைத் தேடுங்கள்...',
      'openings_count': 'வாய்ப்புகள்',
      'resume': 'தொடரவும்',
      'last_studied_yesterday': 'கடைசியாகப் படித்தது: நேற்று',
      'sub_posts': 'துணைப் பதிவுகள்',
      //'mock_tests': 'மாதிரித் தேர்வுகள்',
      'study_material': 'பாடப் பொருட்கள்',
      'previous_year': 'முந்தைய ஆண்டு',
      'syllabus': 'பாடத்திட்டம்',
      'got_it': 'சரி',
      'start': 'தொடங்கு',
      //'continue_learning': 'கற்றலைத் தொடரவும்',
      'government_org': 'அரசு நிறுவனம்',
      'explore_categories': 'சிறந்த அரசு தேர்வு வகைகளை ஆராயுங்கள்',
      'continue_learning_sub': 'கற்றலை\nதொடரவும்',
      'notes_pdfs_sub': 'குறிப்புகள், PDFகள்\nமற்றும் பல',
      'module_prefix': 'பகுதி',
      'content_locked_upgrade':
          'இந்த உள்ளடக்கம் பூட்டப்பட்டுள்ளது. அணுகுவதற்கு மேம்படுத்தவும்.',
      'premium_content': 'பிரீமியம் உள்ளடக்கம்',
      'premium_module_desc':
          'இந்த தொகுதி எங்கள் எலைட் கற்றல் பாதையின் ஒரு பகுதியாகும். அனைத்து தொகுதிகளையும் மேம்பட்ட தேர்வுத் தொடர்களையும் திறக்க உங்கள் சந்தாவை மேம்படுத்தவும்.',
      'maybe_later': 'பிறகு பார்க்கலாம்',
      'upgrade_now': 'இப்போது மேம்படுத்தவும்',
      'login_module_desc':
          'பிரீமியம் தொகுதிகளை அணுகவும் உங்கள் முன்னேற்றத்தைக் கண்காணிக்கவும் உள்நுழையவும்.',
      'login_now': 'இப்போது உள்நுழைக',
      'no_courses_available': 'பாடங்கள் எதுவும் இல்லை',
      'check_back_later_courses':
          'தற்போது உங்கள் விருப்பங்களுக்கு ஏற்ப பாடங்கள் எதுவும் இல்லை. பிறகு பார்க்கவும்!',

      'failed_load_materials': 'பாடப் பொருட்களை ஏற்றுவதில் தோல்வி',
      'no_matching_found': 'பொருந்தும் பொருட்கள் எதுவும் இல்லை',
      'video_player_coming_soon': 'வீடியோ பிளேயர் விரைவில் வரும்!',
      'failed_load_jobs': 'வேலைகளை ஏற்றுவதில் தோல்வி',
      'resume_course': 'பாடத்தைத் தொடரவும்',
      'company_default_desc':
          '7,000+ நிலையங்களை இணைக்கும் உலகின் மிகப்பெரிய இரயில்வே நெட்வொர்க்குகளில் ஒன்று - தேசிய உள்கட்டமைப்பு மற்றும் பொது சேவை சிறப்பின் தூண்.',
      'no_files_available_desc':
          'தற்போது இந்தப் பகுதியில் கோப்புகள் எதுவும் இல்லை. அவற்றை விரைவில் வழங்க நாங்கள் கடுமையாக உழைத்து வருகிறோம்!',
      'no_rankings_yet': 'இன்னும் தரவரிசைகள் இல்லை!',
      'leaderboard_empty_desc':
          'தற்போது லீடர்போர்டு காலியாக உள்ளது.\nகற்கத் தொடங்குங்கள் மற்றும் இங்கே இடம் பெறும் முதல் நபராக இருங்கள்!',
      'climb_leaderboard': 'லீடர்போர்டில் முன்னேறுங்கள்',
      'study_learn_title': 'படியுங்கள் மற்றும் கற்றுக்கொள்ளுங்கள்',
      'study_learn_desc':
          'தொகுப்புகளை முடித்து உங்கள் அறிவை விரிவுபடுத்துங்கள்',
      'take_tests_title': 'தேர்வுகளை எழுதுங்கள்',
      'take_tests_desc':
          'தேர்வுகளை முயற்சி செய்து உங்கள் மதிப்பெண்ணை மேம்படுத்துங்கள்',
      'earn_points_title': 'புள்ளிகளைப் பெறுங்கள்',
      'earn_points_desc': 'அதிக மதிப்பெண் பெற்று தரவரிசையில் முன்னேறுங்கள்',
      'consistency_today': 'இன்று விடாமுயற்சியுடன் இருங்கள்,',
      'lead_tomorrow': 'நாளை லீடர்போர்டை வழிநடத்துங்கள்!',
      'tagline': 'நட்சத்திரங்களை எட்டுங்கள்',
      'skip': 'தவிர்',
      'get_started': 'தொடங்குங்கள்',
      'next_step': 'அடுத்த படி',
      'onboarding_title_1': 'வெற்றி பெறுவது\nஎளிது',
      'onboarding_desc_1':
          'சிறப்புக்காக வடிவமைக்கப்பட்ட எங்கள் தனிப்பயனாக்கப்பட்ட கற்றல் சூழல் மூலம் உங்கள் திறனை வெளிப்படுத்துங்கள்.',
      'onboarding_highlight_1': 'புத்திசாலித்தனமாக கற்றுக்கொள்ளுங்கள்',
      'onboarding_title_2': 'தேர்வுகளில்\nதேர்ச்சி பெறுங்கள்',
      'onboarding_desc_2':
          'பரந்த அளவிலான மாதிரி தேர்வுகள் மற்றும் நிகழ்நேர செயல்திறன் பகுப்பாய்வுகளில் மூழ்குங்கள்.',
      'onboarding_highlight_2': 'ஒவ்வொரு தேர்விலும் சிறப்பு',
      'onboarding_title_3': 'கட்டமைக்கப்பட்ட\nகற்றல் பாதைகள்',
      'onboarding_desc_3':
          'உங்கள் கல்வித் தேவைகளுக்கு ஏற்ப வடிவமைக்கப்பட்ட வகை அடிப்படையிலான கற்றல் தொகுப்புகளை ஆராயுங்கள்.',
      'onboarding_highlight_3': 'வகை அடிப்படையிலான படிப்பு',
      'no_active_notifications': 'செயலில் உள்ள அறிவிப்புகள் இல்லை',

      'access_premium_journey': 'உங்கள் பிரீமியம் கற்றல் பயணத்தை அணுகுங்கள்',
      'otp_login': 'OTP உள்நுழைவு',
      'password_tab': 'கடவுச்சொல்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'otp_hint': '6-இலக்க OTP குறியீடு',
      'resend_otp_in': 'OTP-ஐ மீண்டும் அனுப்பவும்',
      'resend_otp': 'OTP-ஐ மீண்டும் அனுப்பவும்',
      'password_hint': 'கடவுச்சொல்',
      'activate_session': 'அமர்வைச் செயல்படுத்தவும்',
      'get_otp_code': 'OTP குறியீட்டைப் பெறுக',
      'sign_in': 'உள்நுழைக',
      'dont_have_account': 'கணக்கு இல்லையா? ',
      'create_profile': 'சுயவிவரத்தை உருவாக்கவும்',
      'enter_email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      'enter_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'otp_sent_success': 'உங்கள் மின்னஞ்சலுக்கு OTP அனுப்பப்பட்டது',
      'otp_send_failed':
          'OTP அனுப்புவதில் தோல்வி. மின்னஞ்சலைச் சரிபார்க்கவும்.',
      'enter_otp': 'தயவுசெய்து OTP-ஐ உள்ளிடவும்',
      'invalid_otp_failed': 'தவறான OTP அல்லது உள்நுழைவு தோல்வியடைந்தது',
      'invalid_credentials': 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்',
      'about_exam': 'தேர்வு பற்றி',
      'syllabus_overview': 'பாடத்திட்ட மேலோட்டம்',
      'target_year': 'இலக்கு ஆண்டு',
      'duration': 'காலம்',
      'questions': 'கேள்விகள்',
      'rating': 'மதிப்பீடு',
      'start_preparation': 'தயாரிப்பைத் தொடங்குங்கள்',
      'submit_test_title': 'தேர்வைச் சமர்ப்பிக்கவா?',
      'submit_test_desc': 'உங்கள் தேர்வைச் சமர்ப்பிக்க விரும்புகிறீர்களா?',
      'unanswered_questions_warning':
          'உங்களிடம் {count} பதிலளிக்கப்படாத கேள்விகள் உள்ளன.',
      'review_more': 'மேலும் மதிப்பாய்வு செய்யவும்',
      'submit_now': 'இப்போது சமர்ப்பிக்கவும்',
      'quit_test_title': 'தேர்வில் இருந்து வெளியேறவா?',
      'quit_test_desc':
          'வெளியேற விரும்புகிறீர்களா? உங்கள் தற்போதைய தேர்வு முன்னேற்றம் இழக்கப்படும்.',
      'stay': 'இருங்கள்',
      'exit': 'வெளியேறு',
      'back_to_learning': 'மீண்டும் கற்றலுக்கு',
      'no_questions_found': 'கேள்விகள் எதுவும் இல்லை',
      'no_questions_desc':
          'இந்தத் தேர்வுத் தொகுப்பில் கேள்விகள் எதுவும் இல்லை. பிறகு பார்க்கவும்.',
      'go_back': 'பின்னால் செல்',
      'test_instructions': 'தேர்வு வழிமுறைகள்',
      'submitting_test': 'உங்கள் தேர்வைச் சமர்ப்பிக்கிறது...',
      'important_rules': 'முக்கிய விதிகள்',
      'rule_1': 'ஒவ்வொரு கேள்விக்கும் 1 மதிப்பெண்.',
      'rule_2': 'மொத்த காலம் {min} நிமிடங்கள்.',
      'rule_3': 'நேரம் முடிந்ததும் தேர்வு தானாகவே சமர்ப்பிக்கப்படும்.',
      'rule_4': 'கேள்விகள் ஆங்கிலத்தில் கிடைக்கின்றன.',
      'start_test_now': 'இப்போது தேர்வைத் தொடங்குங்கள்',
      'minutes': 'நிமிடங்கள்',
      'easy': 'எளிதானது',
      'medium': 'நடுத்தரம்',
      'hard': 'கடினமானது',
      'progress': 'முன்னேற்றம்',
      'continue_lesson': 'பாடத்தைத் தொடரவும்',
      'explore_gov_exams': 'சிறந்த அரசு தேர்வு வகைகளை ஆராயுங்கள்',
      'no_courses_right_now': 'தற்போது பாடங்கள் எதுவும் இல்லை',
      'available_materials': 'கிடைக்கக்கூடிய பாடப் பொருட்கள்',
      'items_count': '{count} பொருட்கள்',
      'mod_prefix': 'MOD',
      'no_test_series': 'இன்னும் தேர்வுத் தொடர்கள் இல்லை.',
      'no_sets_available': 'இந்தத் தொகுப்பிற்கான செட்கள் இன்னும் இல்லை.',
      'module_integrated_soon':
          'இந்தத் தொகுதி தற்போது ஒருங்கிணைக்கப்பட்டு வருகிறது.\nவிரைவில் மீண்டும் பார்க்கவும்.',
      // 'learning_journey': 'கற்றல் பயணம்',
      // 'modules': 'தொகுதிகள்',
      // 'your_progress': 'உங்கள் முன்னேற்றம்',
      // 'keep_learning_great': 'தொடர்ந்து கற்றுக்கொள்ளுங்கள்! நீங்கள் சிறப்பாகச் செய்கிறீர்கள்.',
      // 'all_modules_completed': 'இந்த பாடத்திட்டத்தின் அனைத்து தொகுதிகளும் முடிந்துவிட்டன!',
      // 'finish_journey': 'பயணத்தை முடிக்கவும்',
      // 'complete_next_module': 'முடிந்தது மற்றும் அடுத்த தொகுதி',
      'exit_confirm_title': 'பயணத்திலிருந்து வெளியேறவா?',
      'exit_confirm_desc':
          'வெளியேற விரும்புகிறீர்களா? இந்த அமர்வில் உங்கள் முன்னேற்றம் சேமிக்கப்படும்.',
      'dismiss_all': 'அனைத்தையும் நீக்கு',
      'instruction_guide_title': 'விரைவான வழிமுறை வழிகாட்டி',
      'instruction_guide_desc':
          'பக்க மெனுவிலிருந்து உங்கள் அனைத்து பாட தொகுதிகள், மாதிரி தேர்வுகள் மற்றும் வீடியோ பாடங்களை அணுகவும்.',
      'instruction_step_1': 'தொகுதிகளை மாற்ற மெனு ஐகானைத் தட்டவும்',
      'instruction_step_2':
          'ஒவ்வொரு பிரிவிலும் உங்கள் முன்னேற்றத்தைக் கண்காணிக்கவும்',
      // 'got_it_lets_go': 'புரிந்தது, போகலாம்!',
      // 'keep_learning_btn': 'தொடர்ந்து கற்கவும்',
      // 'yes_exit': 'ஆம், வெளியேறு',
      'discover_learning_paths': 'சிறந்த கற்றல் பாதைகளைக் கண்டறியுங்கள்',
      'smart_prep_future':
          'உங்கள் பிரகாசமான எதிர்காலத்திற்கான சிறந்த தயாரிப்பு',
      'join_community': 'சமூகத்தில் சேரவும்',
      // 'connect_aspirants': '50,000+ மாணவர்களுடன் இணையுங்கள்',
      'join_whatsapp': 'WhatsApp சமூகத்தில் சேரவும்',
      'about_platform_desc':
          'அரசுத் தேர்வுகளுக்கான இந்தியாவின் முன்னணி கற்றல் தளம்.',
      'copyright_text':
          '© 2026 ஸ்கைஹை கற்றல். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
      // 'email': 'மின்னஞ்சல்',
      // 'call': 'அழைக்க',
      // 'address': 'முகவரி',
      'facebook': 'பேஸ்புக்',
      'cat_business': 'வணிகம்',
      'cat_marketing': 'சந்தைப்படுத்தல்',
      'cat_design': 'வடிவமைப்பு',
      'no_internet': 'இணைய இணைப்பு இல்லை',
      'connect_internet': 'இணையத்தை இணைக்கவும்',
      'connect_internet_desc':
          'தயவுசெய்து உங்கள் இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'try_again': 'மீண்டும் முயற்சி செய்',
      'checking_connection': 'சரிபார்க்கிறது...',
    },
    'Telugu': {
      'free_study_materials': 'ఉచిత అధ్యయన సామాగ్రి',
      'search_hint': 'కోర్సులు, పరీక్షలు, సబ్జెక్టుల కోసం వెతకండి...',
      'categories': 'వర్గాలు',
      'continue_studying': 'చదువు కొనసాగించండి',
      'free_exams': 'ఉచిత పరీక్షలు',
      'study_materials': 'అధ్యయన సామాగ్రి',
      'view_all': 'అన్నీ చూడండి',
      'login': 'లాగిన్',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగులు',
      'logout': 'లాగ్ అవుట్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'premium_status': 'ప్రీమియం స్థితి',
      'about_us': 'మా గురించి',
      'write_review': 'సమీక్ష రాయండి',
      'contact_whatsapp': 'వాట్సాప్‌లో సంప్రదించండి',
      'no_recent_study': 'మీ పురోగతిని చూడటానికి ఒక కోర్సును ప్రారంభించండి',
      'start_learning': 'చదువు ప్రారంభించండి',
      'all_categories': 'అన్ని వర్గాలు',
      'explore_courses': 'మా విస్తృత కోర్సులను అన్వేషించండి',
      'notification': 'నోటిఫికేషన్',
      'privacy': 'గోప్యత',
      'purchased': 'కొనుగోలు చేయబడింది',
      'achieved': 'సాధించినవి',
      'certificates': 'సర్టిఫికెట్లు',
      'about_desc':
          'ప్రభుత్వ పరీక్షల కోసం భారతదేశపు ప్రముఖ లెర్నింగ్ ప్లాట్‌ఫారమ్.',
      'whatsapp_title': 'కమ్యూనిటీలో చేరండి',
      'my_courses': 'నా కోర్సులు',
      'leaderboard': 'లీడర్‌బోర్డ్',
      'mock_tests': 'మాక్ టెస్ట్‌లు',
      'continue_learning': 'చదువు కొనసాగించండి',
      'practice_improve': 'ప్రాక్టీస్ & మెరుగుపరచండి',
      'compete_achieve': 'పోటీ పడండి & సాధించండి',
      'welcome_msg': 'స్కై హై కి స్వాగతం',
      'login_track': 'మీ పురోగతిని ట్రాక్ చేయడానికి లాగిన్ అవ్వండి',
      'hi': 'హాయ్',
      'continue_journey': 'మీ లెర్నింగ్ ప్రయాణాన్ని కొనసాగిద్దాం!',
      'identity_required': 'గుర్తింపు అవసరం',
      'signin_sync':
          'మీ పురోగతిని సమకాలీకరించడానికి, ప్రీమియం సర్టిఫికేట్లను యాక్సెస్ చేయడానికి మరియు ఎలైట్ కమ్యూనిటీలో చేరడానికి సైన్ ఇన్ చేయండి.',
      'signin_now': 'ఇప్పుడే సైన్ ఇన్ చేయండి',
      'logout_confirm': 'మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
      'close': 'మూసివేయి',
      'cancel': 'రద్దు చేయండి',
      'email': 'ఈమెయిల్',
      'call': 'కాల్',
      'address': 'చిరునామా',
      'whatsapp_community': 'వాట్సాప్ కమ్యూనిటీలో చేరండి',
      'connect_aspirants': '50,000+ ఆస్పిరెంట్లతో కనెక్ట్ అవ్వండి',
      'happy_students': 'మా సంతోషకరమైన విద్యార్థులు',
      'what_students_say': 'మా విద్యార్థులు ఏమంటున్నారు',
      'login_required': 'లాగిన్ అవసరం',
      'signin_payment':
          'మీ చెల్లింపును కొనసాగించడానికి దయచేసి సైన్ ఇన్ చేయండి.',
      'search_categories': 'వర్గాలను వెతకండి...',
      'no_categories_found': 'వర్గాలు ఏవీ కనుగొనబడలేదు',
      'try_searching_else': 'మరేదైనా వెతకడానికి ప్రయత్నించండి',
      'explore_exam_categories': 'ప్రభుత్వ పరీక్ష వర్గాలను అన్వేషించండి',
      'find_category_prep':
          'మీ పరీక్ష ప్రిపరేషన్ కోసం సరైన వర్గాన్ని కనుగొనండి',
      'no_materials_available': 'మెటీరియల్స్ అందుబాటులో లేవు',
      'no_companies_available': 'కంపెనీలు అందుబాటులో లేవు',
      'check_back_later': 'కొత్త కంటెంట్ కోసం మళ్లీ చూడండి.',
      'cant_find_looking': 'మీరు వెతుకుతున్నది దొరకలేదా?',
      'help_find_category': 'సరైన వర్గాన్ని కనుగొనడంలో మాకు సహాయపడనివ్వండి.',
      'contact_us': 'మమ్మల్ని సంప్రదించండి',
      'organization': 'సంస్థ',
      'item': 'అంశం',
      'companies': 'కంపెనీలు',
      'search_books_notes': 'పుస్తకాలు, నోట్స్ కోసం వెతకండి...',
      'continue_learning_sub': 'నేర్చుకోవడం\nకొనసాగించండి',
      'notes_pdfs_sub': 'నోట్స్, PDFలు\nమరియు మరిన్ని',
      'module_prefix': 'మాడ్యూల్',
      'content_locked_upgrade':
          'ఈ కంటెంట్ లాక్ చేయబడింది. అన్‌లాక్ చేయడానికి అప్‌గ్రేడ్ చేయండి.',
      'premium_content': 'ప్రీమియం కంటెంట్',
      'premium_module_desc':
          'ఈ మాడ్యూల్ మా ఎలైట్ లెర్నింగ్ పాత్‌లో భాగం. అన్ని మాడ్యూల్స్ మరియు అడ్వాన్స్‌డ్ టెస్ట్ సిరీస్‌లను అన్‌లాక్ చేయడానికి మీ సబ్‌స్క్రిప్షన్‌ను అప్‌గ్రేడ్ చేయండి.',
      'maybe_later': 'తర్వాత చూద్దాం',
      'upgrade_now': 'ఇప్పుడే అప్‌గ్రేడ్ చేయండి',
      'login_module_desc':
          'ప్రీమియం మాడ్యూల్స్‌ను యాక్సెస్ చేయడానికి మరియు మీ పురోగతిని ట్రాక్ చేయడానికి దయచేసి లాగిన్ అవ్వండి.',
      'login_now': 'இప్పుడే లాగిన్ అవ్వండి',
      'no_courses_available': 'కోర్సులు అందుబాటులో లేవు',
      'check_back_later_courses':
          'ప్రస్తుతం మీ ప్రాధాన్యతల కోసం కోర్సులు అందుబాటులో లేవు. దయచేసి తర్వాత మళ్ళీ చూడండి!',
      'got_it': 'సరే',
      'failed_load_materials': 'మెటీరియల్స్ లోడ్ చేయడం విఫలమైంది',
      'no_matching_found': 'సరిపోలే మెటీరియల్స్ ఏవీ కనుగొనబడలేదు',
      'video_player_coming_soon': 'వీడియో ప్లేయర్ త్వరలో వస్తుంది!',
      'failed_load_jobs': 'ఉద్యోగాలను లోడ్ చేయడం విఫలమైంది',
      'resume_course': 'కోర్సును తిరిగి ప్రారంభించండి',
      'company_default_desc':
          'భారతదేశం అంతటా 7,000+ స్టేషన్లను కలుపుతూ ప్రపంచంలోనే అతిపెద్ద రైల్వే నెట్‌వర్క్‌లలో ఒకటి - జాతీయ మౌలిక సదుపాయాలు మరియు ప్రజా సేవా శ్రేష్ఠతకు మూలస్తంభం.',
      'no_files_available_desc':
          'ఈ సమయంలో ఈ విభాగం కోసం ఫైల్‌లు అందుబాటులో లేవు. మేము వాటిని త్వరలో మీకు అందించడానికి తీవ్రంగా కృషి చేస్తున్నాము!',
      'no_rankings_yet': 'ఇంకా ర్యాంకింగ్‌లు లేవు!',
      'leaderboard_empty_desc':
          'ప్రస్తుతానికి లీడర్‌బోర్డ్ ఖాళీగా ఉంది.\nనేర్చుకోవడం ప్రారంభించండి మరియు ఇక్కడ చోటు సంపాదించే మొదటి వ్యక్తి అవ్వండి!',
      'climb_leaderboard': 'లీడర్‌బోర్డ్‌లో పైకి వెళ్ళండి',
      'study_learn_title': 'చదవండి మరియు నేర్చుకోండి',
      'study_learn_desc':
          'మాడ్యూళ్లను పూర్తి చేయండి మరియు మీ జ్ఞానాన్ని పెంచుకోండి',
      'take_tests_title': 'పరీక్షలు రాయండి',
      'take_tests_desc': 'పరీక్షలకు హాజరై మీ స్కోరును మెరుగుపరుచుకోండి',
      'earn_points_title': 'పాయింట్లు సంపాదించండి',
      'earn_points_desc': 'ఎక్కువ స్కోరు సాధించి ర్యాంకుల్లో పైకి వెళ్ళండి',
      'consistency_today': 'ఈ రోజు స్థిరంగా ఉండండి,',
      'lead_tomorrow': 'రేపు లీడర్‌బోర్డ్‌ను నడిపించండి!',
      'tagline': 'నక్షత్రాలను అందుకోండి',
      'skip': 'దాటవేయి',
      'get_started': 'ప్రారంభించండి',
      'next_step': 'తదుపరి అడుగు',
      'onboarding_title_1': 'విజయం సాధించడం\nసులభం',
      'onboarding_desc_1':
          'శ్రేష్ఠత కోసం రూపొందించబడిన మా వ్యక్తిగతీకరించిన అభ్యాస పర్యావరణ వ్యవస్థతో మీ సామర్థ్యాన్ని అన్‌లాక్ చేయండి.',
      'onboarding_highlight_1': 'తెలివిగా నేర్చుకోండి',
      'onboarding_title_2': 'పరీక్షల్లో\nపట్టు సాధించండి',
      'onboarding_desc_2':
          'విస్తృతమైన మాక్ టెస్టులు మరియు నిజ-సమయ పనితీరు విశ్లేషణలలో మునిగిపోండి.',
      'onboarding_highlight_2': 'ప్రతి పరీక్షలో శ్రేష్ఠత',
      'onboarding_title_3': 'నిర్మాణాత్మక\nఅభ్యాస మార్గాలు',
      'onboarding_desc_3':
          'మీ నిర్దిష్ట విద్యా అవసరాలకు అనుగుణంగా రూపొందించబడిన వర్గ-ఆధారిత అధ్యయన మాడ్యూళ్లను అన్వేషించండి.',
      'onboarding_highlight_3': 'వర్గ ఆధారిత అధ్యయనం',
      'no_active_notifications': 'క్రియాశీల నోటిఫికೇషన్లు లేవు',

      'access_premium_journey': 'మీ ప్రీమియం అభ్యాస ప్రయాణాన్ని ప్రారంభించండి',
      'otp_login': 'OTP లాగిన్',
      'password_tab': 'పాస్‌వర్డ్',
      'email_address': 'ఈమెయిల్ చిరునామా',
      'otp_hint': '6-అంకెల OTP కోడ్',
      'resend_otp_in': 'OTPని మళ్ళీ పంపండి',
      'resend_otp': 'OTPని మళ్ళీ పంపండి',
      'password_hint': 'పాస్‌వర్డ్',
      'activate_session': 'సెషన్‌ను ప్రారంభించండి',
      'get_otp_code': 'OTP కోడ్ పొందండి',
      'sign_in': 'సైన్ ఇన్',
      'dont_have_account': 'ఖాతా లేదా? ',
      'create_profile': 'ప్రొఫೈల్ సృಷ್ಟించండి',
      'enter_email': 'దయచేసి మీ ఈమెయిల్ ఎంటర్ చేయండి',
      'enter_password': 'దయచేసి మీ పాస్‌వర్డ్ ఎంటర్ చేయండి',
      'otp_sent_success': 'మీ ఈమెయిల్‌కు OTP పంపబడింది',
      'otp_send_failed': 'OTP పంపడం విಫలమైంది. మీ ఈమెయిల్ తనిಖీ చేయండి.',
      'enter_otp': 'దయచేసి OTP ఎంటర్ చేయండి',
      'invalid_otp_failed': 'చెల్లని OTP లేదా లాగిన్ విఫలమైంది',
      'invalid_credentials': 'చెల్లని ఈమెయిల్ లేదా పాస్‌వర్డ్',
      'about_exam': 'పరీక్ష గురించి',
      'syllabus_overview': 'సిలబస్ అవలోకనం',
      'target_year': 'లక్ష్య సంవత్సరం',
      'duration': 'వ్యవధి',
      'questions': 'ప్రశ్నలు',
      'rating': 'రేటింగ్',
      'start_preparation': 'తయారీని ప్రారంభించండి',
      'submit_test_title': 'పరీక్షను సమర్పించాలా?',
      'submit_test_desc': 'మీరు ఖచ్చితంగా మీ పరీక్షను సమర్పించాలనుకుంటున్నారా?',
      'unanswered_questions_warning':
          'మీకు {count} సమాధానం లేని ప్రశ్నలు ఉన్నాయి.',
      'review_more': 'మరింత సమీక్షించండి',
      'submit_now': 'ఇప్పుడే సమర్పించండి',
      'quit_test_title': 'పరీక్ష నుండి తప్పుకోవాలా?',
      'quit_test_desc':
          'మీరు ఖచ్చితంగా నిష్క్రమించాలనుకుంటున్నారా? మీ ప్రస్తుత పరీక్ష పురోగతి కోల్పోతుంది.',
      'stay': 'ఉండండి',
      'exit': 'నిష్క్రమించండి',
      'back_to_learning': 'తిరిగి అభ్యాసానికి',
      'no_questions_found': 'ప్రశ్నలు కనుగొనబడలేదు',
      'no_questions_desc':
          'ఈ సమయంలో ఈ పరీక్షా సెట్ కోసం ఎటువంటి ప్రశ్నలు కనుగొనబడలేదు. దయచేసి తర్వాత మళ్ళీ చూడండి.',
      'go_back': 'వెనక్కి వెళ్ళండి',
      'test_instructions': 'పరీక్ష సూచనలు',
      'submitting_test': 'మీ పరీక్షను సమర్పిస్తోంది...',
      'important_rules': 'ముఖ్యమైన నియమాలు',
      'rule_1': 'ప్రతి ప్రశ్నకు 1 మార్కు ఉంటుంది.',
      'rule_2': 'మొత్తం వ్యవధి {min} నిమిషాలు.',
      'rule_3': 'సమయం ముగిసినప్పుడు పరీక్ష స్వయంచాలకంగా సమర్పించబడుతుంది.',
      'rule_4': 'ప్రశ్నలు ఇంగ్లీష్‌లో అందుబాటులో ఉన్నాయి.',
      'start_test_now': 'ఇప్పుడే పరీక్షను ప్రారంభించండి',
      'minutes': 'నిమిషాలు',
      'easy': 'సులభం',
      'medium': 'మధ్యస్థం',
      'hard': 'కష్టం',
      'progress': 'పురోగతి',
      'continue_lesson': 'పాఠాన్ని కొనసాగించండి',
      'explore_gov_exams': 'అగ్ర ప్రభుత్వ పరీక్ష వర్గాలను అన్వేషించండి',
      'no_courses_right_now': 'ప్రస్తుతం కోర్సులు అందుబాటులో లేవు',
      'available_materials': 'అందుబాటులో ఉన్న సామాగ్రి',
      'items_count': '{count} అంశాలు',
      'mod_prefix': 'MOD',
      'no_test_series': 'ఇంకా పరీక్షా శ్రేణులు అందుబాటులో లేవు.',
      'no_sets_available': 'ఈ మాడ్యూల్ కోసం ఇంకా సెట్లు అందుబాటులో లేవు.',
      'module_integrated_soon':
          'ఈ మాడ్యూల్ ప్రస్తుతం సమీకృతం చేయబడుతోంది.\nదయచేసి త్వరలో మళ్ళీ చూడండి.',
      'learning_journey': 'అభ్యాస ప్రయాణం',
      'modules': 'మాడ్యూల్స్',
      'your_progress': 'మీ పురోగతి',
      'keep_learning_great': 'నేర్చుకుంటూ ఉండండి! మీరు బాగా చేస్తున్నారు.',
      'all_modules_completed': 'ఈ కోర్సులోని అన్ని మాడ్యూల్స్ పూర్తయ్యాయి!',
      'finish_journey': 'ప్రయాణాన్ని ముగించండి',
      'complete_next_module': 'పూర్తయింది & తదుపరి మాడ్యూల్',
      'exit_confirm_title': 'ప్రయాణం నుండి నిష్క్రమించాలా?',
      'exit_confirm_desc':
          'మీరు ఖచ్చితంగా నిష్క్రమించాలనుకుంటున్నారా? ఈ సెషన్‌లో మీ పురోగతి సేవ్ చేయబడుతుంది.',
      'dismiss_all': 'అన్నీ తొలగించండి',
      'instruction_guide_title': 'శీఘ్ర సూచన మార్గదర్శి',
      'instruction_guide_desc':
          'సైడ్ మెనూ నుండి మీ అన్ని స్టడీ మాడ్యూల్స్, మాక్ టెస్ట్‌లు మరియు వీడియో లెసన్స్‌ని యాక్సెస్ చేయండి.',
      'instruction_step_1': 'మాడ్యూల్స్ మారడానికి మెనూ ఐకాన్‌ను నొక్కండి',
      'instruction_step_2': 'ప్రతి విభాగంలో మీ పురోగతిని ట్రాక్ చేయండి',
      'got_it_lets_go': 'అర్థమైంది, వెళ్దాం!',
      'keep_learning_btn': 'నేర్చుకుంటూ ఉండండి',
      'yes_exit': 'అవును, నిష్క్రమించు',
      'no_internet': 'కనెక్షన్ లేదు',
      'connect_internet': 'ఇంటర్నెట్ కనెక్ట్ చేయండి',
      'connect_internet_desc':
          'దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేసి, మళ్లీ ప్రయత్నించండి.',
      'try_again': 'మళ్ళీ ప్రయత్నించండి',
      'checking_connection': 'తనిఖీ చేస్తోంది...',
    },
    'Hindi': {
      'free_study_materials': 'मुफ्त अध्ययन सामग्री',
      'search_hint': 'कोर्स, टेस्ट, विषय खोजें...',
      'categories': 'श्रेणियाँ',
      'continue_studying': 'पढ़ाई जारी रखें',
      'free_exams': 'मुफ्त परीक्षा',
      'study_materials': 'अध्ययन सामग्री',
      'view_all': 'सभी देखें',
      'login': 'लॉगिन',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'premium_status': 'प्रीमियम स्थिति',
      'about_us': 'हमारे बारे में',
      'write_review': 'समीक्षा लिखें',
      'contact_whatsapp': 'व्हाट्सएप पर संपर्क करें',
      'no_recent_study': 'अपनी प्रगति देखने के लिए एक कोर्स शुरू करें',
      'start_learning': 'पढ़ना शुरू करें',
      'all_categories': 'सभी श्रेणियाँ',
      'explore_courses': 'हमारे पाठ्यक्रमों की विस्तृत श्रृंखला देखें',
      'notification': 'अधिसूचना',
      'privacy': 'गोपनीयता',
      'purchased': 'खरीदा गया',
      'achieved': 'हासिल किया',
      'certificates': 'प्रमाण पत्र',
      'about_desc': 'सरकारी परीक्षाओं के लिए भारत का अग्रणी शिक्षण मंच।',
      'whatsapp_title': 'समुदाय से जुड़ें',
      'my_courses': 'मेरे कोर्स',
      'leaderboard': 'लीडरबोर्ड',
      'mock_tests': 'मॉक टेस्ट',
      'continue_learning': 'सीखना जारी रखें',
      'practice_improve': 'अभ्यास और सुधार',
      'compete_achieve': 'प्रतिस्पर्धा और उपलब्धि',
      'welcome_msg': 'स्काई हाई में आपका स्वागत है',
      'login_track': 'प्रगति ट्रैक करने के लिए लॉगिन करें',
      'hi': 'नमस्ते',
      'continue_journey': 'अपनी सीखने की यात्रा जारी रखें!',
      'identity_required': 'पहचान आवश्यक',
      'signin_sync':
          'अपनी प्रगति को सिंक करने, प्रीमियम प्रमाणपत्र प्राप्त करने और विशिष्ट समुदाय में शामिल होने के लिए साइन इन करें।',
      'signin_now': 'अभी साइन इन करें',
      'logout_confirm': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
      'close': 'बंद करें',
      'cancel': 'रद्द करें',
      'email': 'ईमेल',
      'call': 'कॉल',
      'address': 'पता',
      'whatsapp_community': 'व्हाट्सएप समुदाय में शामिल हों',
      'connect_aspirants': '50,000+ उम्मीदवारों से जुड़ें',
      'happy_students': 'हमारे खुश छात्र',
      'what_students_say': 'हमारे छात्र क्या कहते हैं',
      'login_required': 'लॉगिन आवश्यक',
      'signin_payment': 'भुगतान जारी रखने के लिए कृपया साइन इन करें।',
      'search_categories': 'श्रेणियां खोजें...',
      'no_categories_found': 'कोई श्रेणी नहीं मिली',
      'try_searching_else': 'कुछ और खोजने का प्रयास करें',
      'explore_exam_categories': 'सरकारी परीक्षा श्रेणियों का अन्वेषण करें',
      'find_category_prep': 'अपनी परीक्षा की तैयारी के लिए सही श्रेणी खोजें',
      'no_materials_available': 'कोई सामग्री उपलब्ध नहीं है',
      'no_companies_available': 'कोई कंपनी उपलब्ध नहीं है',
      'check_back_later': 'नई सामग्री के लिए बाद में जाँचें।',
      'cant_find_looking': 'जो आप ढूंढ रहे हैं वह नहीं मिल रहा है?',
      'help_find_category': 'हमें सही श्रेणी खोजने में आपकी सहायता करने दें।',
      'contact_us': 'संपर्क करें',
      'organization': 'संगठन',
      'item': 'आइटम',
      'companies': 'कंपनियां',
      'search_books_notes': 'किताबें, नोट्स खोजें...',
      'continue_learning_sub': 'सीखना\nजारी रखें',
      'notes_pdfs_sub': 'नोट्स, पीडीएफ\nऔर अधिक',
      'module_prefix': 'मापांक',
      'content_locked_upgrade':
          'यह सामग्री लॉक है। अनलॉक करने के लिए अपग्रेड करें।',
      'premium_content': 'प्रीमियम सामग्री',
      'premium_module_desc':
          'यह मॉड्यूल हमारे एलीट लर्निंग पाथ का हिस्सा है। सभी मॉड्यूल और उन्नत परीक्षण श्रृंखला को अनलॉक करने के लिए अपनी सदस्यता अपग्रेड करें।',
      'maybe_later': 'बाद में',
      'upgrade_now': 'अभी अपग्रेड करें',
      'login_module_desc':
          'प्रीमियम मॉड्यूल तक पहुँचने और अपनी प्रगति को ट्रैक करने के लिए कृपया लॉगिन करें।',
      'login_now': 'अभी लॉगिन करें',
      'no_courses_available': 'कोई कोर्स उपलब्ध नहीं है',
      'check_back_later_courses':
          'वर्तमान में आपकी पसंद के लिए कोई कोर्स उपलब्ध नहीं है। कृपया बाद में फिर से देखें!',
      'got_it': 'ठीक है',
      'failed_load_materials': 'सामग्री लोड करने में विफल',
      'no_matching_found': 'कोई मेल खाती सामग्री नहीं मिली',
      'video_player_coming_soon': 'वीडियो प्लेयर जल्द ही आ रहा है!',
      'failed_load_jobs': 'नौकरियां लोड करने में विफल',
      'resume_course': 'कोर्स फिर से शुरू करें',
      'company_default_desc':
          '7,000+ स्टेशनों को जोड़ने वाले दुनिया के सबसे बड़े रेलवे नेटवर्क में से एक - राष्ट्रीय बुनियादी ढांचे और सार्वजनिक सेवा उत्कृष्टता का स्तंभ।',
      'no_files_available_desc':
          'इस समय इस अनुभाग के लिए कोई फ़ाइल उपलब्ध नहीं है। हम उन्हें जल्द ही आपके पास लाने के लिए कड़ी मेहनत कर रहे हैं!',
      'no_rankings_yet': 'अभी तक कोई रैंकिंग नहीं है!',
      'leaderboard_empty_desc':
          'अभी के लिए लीडरबोर्ड खाली है।\nसीखना शुरू करें और यहाँ जगह बनाने वाले पहले व्यक्ति बनें!',
      'climb_leaderboard': 'लीडरबोर्ड पर चढ़ें',
      'study_learn_title': 'पढ़ें और सीखें',
      'study_learn_desc': 'मॉड्यूल पूरे करें और अपना ज्ञान बढ़ाएं',
      'take_tests_title': 'टेस्ट लें',
      'take_tests_desc': 'टेस्ट का प्रयास करें और अपना स्कोर सुधारें',
      'earn_points_title': 'अंक अर्जित करें',
      'earn_points_desc': 'उच्च स्कोर करें और रैंक ऊपर चढ़ें',
      'consistency_today': 'आज निरंतर बने रहें,',
      'lead_tomorrow': 'कल लीडरबोर्ड का नेतृत्व करें!',
      'tagline': 'सितारों तक पहुँचें',
      'skip': 'छोड़ें',
      'get_started': 'शुरू करें',
      'next_step': 'अगला कदम',
      'onboarding_title_1': 'सफलता प्राप्त करना\nआसान है',
      'onboarding_desc_1':
          'उत्कृष्टता के लिए डिज़ाइन किए गए हमारे व्यक्तिगत शिक्षण पारिस्थितिकी तंत्र के साथ अपनी क्षमता को अनलॉक करें।',
      'onboarding_highlight_1': 'होशियारी से सीखें',
      'onboarding_title_2': 'परीक्षाओं में\nमहारत हासिल करें',
      'onboarding_desc_2':
          'मॉक टेस्ट और रीयल-टाइम प्रदर्शन विश्लेषण के विशाल पुस्तकालय में गोता लगाएँ।',
      'onboarding_highlight_2': 'हर टेस्ट में उत्कृष्टता',
      'onboarding_title_3': 'संरचित\nसीखने के रास्ते',
      'onboarding_desc_3':
          'अपनी विशिष्ट शैक्षणिक आवश्यकताओं के अनुरूप श्रेणी-आधारित अध्ययन मॉड्यूल का अन्वेषण करें।',
      'onboarding_highlight_3': 'श्रेणी आधारित अध्ययन',
      'no_active_notifications': 'कोई सक्रिय सूचनाएं नहीं',

      'access_premium_journey': 'अपनी प्रीमियम सीखने की यात्रा तक पहुँचें',
      'otp_login': 'ओटीपी लॉगिन',
      'password_tab': 'पासवर्ड',
      'email_address': 'ईमेल पता',
      'otp_hint': '6-अंकीय ओटीपी कोड',
      'resend_otp_in': 'ओटीपी पुनः भेजें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'password_hint': 'पासवर्ड',
      'activate_session': 'सत्र सक्रिय करें',
      'get_otp_code': 'ओटीपी कोड प्राप्त करें',
      'sign_in': 'साइन इन',
      'dont_have_account': 'खाता नहीं है? ',
      'create_profile': 'प्रोफ़ाइल बनाएँ',
      'enter_email': 'कृपया अपना ईमेल दर्ज करें',
      'enter_password': 'कृपया अपना पासवर्ड दर्ज करें',
      'otp_sent_success': 'आपके ईमेल पर ओटीपी भेजा गया',
      'otp_send_failed': 'ओटीपी भेजने में विफल। कृपया अपना ईमेल जांचें।',
      'enter_otp': 'कृपया ओटीपी दर्ज करें',
      'invalid_otp_failed': 'अमान्य ओटीपी या लॉगिन विफल',
      'invalid_credentials': 'अमान्य ईमेल या पासवर्ड',
      'about_exam': 'परीक्षा के बारे में',
      'syllabus_overview': 'पाठ्यक्रम अवलोकन',
      'target_year': 'लक्ष्य वर्ष',
      'duration': 'अवधि',
      'questions': 'प्रश्न',
      'rating': 'रेटिंग',
      'start_preparation': 'तैयारी शुरू करें',
      'submit_test_title': 'टेस्ट सबमिट करें?',
      'submit_test_desc': 'क्या आप वाकई अपना टेस्ट सबमिट करना चाहते हैं?',
      'unanswered_questions_warning': 'आपके पास {count} अनुत्तरित प्रश्न हैं।',
      'review_more': 'अधिक समीक्षा करें',
      'submit_now': 'अभी सबमिट करें',
      'quit_test_title': 'टेस्ट छोड़ें?',
      'quit_test_desc':
          'क्या आप वाकई बाहर निकलना चाहते हैं? आपकी वर्तमान टेस्ट प्रगति खो जाएगी।',
      'stay': 'रुकें',
      'exit': 'बाहर निकलें',
      'back_to_learning': 'सीखने पर वापस जाएं',
      'no_questions_found': 'कोई प्रश्न नहीं मिला',
      'no_questions_desc':
          'हमें इस समय इस टेस्ट सेट के लिए कोई प्रश्न नहीं मिला। कृपया बाद में फिर से देखें।',
      'go_back': 'वापस जाएं',
      'test_instructions': 'टेस्ट निर्देश',
      'submitting_test': 'आपका टेस्ट सबमिट किया जा रहा है...',
      'important_rules': 'महत्वपूर्ण नियम',
      'rule_1': 'प्रत्येक प्रश्न 1 अंक का है।',
      'rule_2': 'कुल अवधि {min} मिनट है।',
      'rule_3': 'समय समाप्त होने पर टेस्ट स्वतः सबमिट हो जाएगा।',
      'rule_4': 'प्रश्न अंग्रेजी में उपलब्ध हैं।',
      'start_test_now': 'अभी टेस्ट शुरू करें',
      'minutes': 'मिनट',
      'easy': 'आसान',
      'medium': 'मध्यम',
      'hard': 'कठिन',
      'progress': 'प्रगति',
      'continue_lesson': 'पाठ जारी रखें',
      'explore_gov_exams': 'शीर्ष सरकारी परीक्षा श्रेणियों का अन्वेषण करें',
      'no_courses_right_now': 'अभी कोई कोर्स उपलब्ध नहीं है',
      'available_materials': 'उपलब्ध सामग्री',
      'items_count': '{count} आइटम',
      'mod_prefix': 'MOD',
      'no_test_series': 'अभी तक कोई टेस्ट सीरीज़ उपलब्ध नहीं है।',
      'no_sets_available': 'इस मॉड्यूल के लिए अभी तक कोई सेट उपलब्ध नहीं है।',
      'module_integrated_soon':
          'यह मॉड्यूल वर्तमान में एकीकृत किया जा रहा है।\nकृपया जल्द ही पुनः देखें।',
      'learning_journey': 'सीखने की यात्रा',
      'modules': 'मॉड्यूल',
      'your_progress': 'आपकी प्रगति',
      'keep_learning_great': 'सीखते रहें! आप बहुत अच्छा कर रहे हैं।',
      'all_modules_completed': 'इस कोर्स के सभी मॉड्यूल पूरे हो गए!',
      'finish_journey': 'यात्रा समाप्त करें',
      'complete_next_module': 'पूरा करें और अगला मॉड्यूल',
      'exit_confirm_title': 'यात्रा से बाहर निकलें?',
      'exit_confirm_desc':
          'क्या आप वाकई बाहर निकलना चाहते हैं? इस सत्र में आपकी प्रगति सहेज ली जाएगी।',
      'dismiss_all': 'सभी हटाएँ',
      'instruction_guide_title': 'त्वरित निर्देश गाइड',
      'instruction_guide_desc':
          'साइड मेनू से अपने सभी अध्ययन मॉड्यूल, मॉक टेस्ट और वीडियो पाठ एक्सेस करें।',
      'instruction_step_1': 'मॉड्यूल बदलने के लिए मेनू आइकन पर टैप करें',
      'instruction_step_2': 'प्रत्येक अनुभाग में अपनी प्रगति को ट्रैक करें',
      'got_it_lets_go': 'समझ गया, चलें!',
      'keep_learning_btn': 'सीखते रहें',
      'yes_exit': 'हाँ, बाहर निकलें',
      'no_internet': 'कोई कनेक्शन नहीं',
      'connect_internet': 'इंटरनेट कनेक्ट करें',
      'connect_internet_desc':
          'कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।',
      'try_again': 'पुनः प्रयास करें',
      'checking_connection': 'जांच की जा रही है...',
    },
    'Malayalam': {
      'free_study_materials': 'സൗജന്യ പഠന സാമഗ്രികൾ',
      'search_hint': 'കോഴ്സുകൾ, പരീക്ഷകൾ തിരയുക...',
      'categories': 'വിഭാഗങ്ങൾ',
      'continue_studying': 'പഠനം തുടരുക',
      'free_exams': 'സൗജന്യ പരീക്ഷകൾ',
      'study_materials': 'പഠന സാമഗ്രികൾ',
      'view_all': 'എല്ലാം കാണുക',
      'login': 'ലോഗിൻ',
      'profile': 'പ്രൊഫീൽ',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'logout': 'ലോഗ് ഔട്ട്',
      'edit_profile': 'പ്രൊഫൈൽ തിരുത്തുക',
      'premium_status': 'പ്രീമിയം സ്റ്റാറ്റസ്',
      'about_us': 'ഞങ്ങളെക്കുറിച്ച്',
      'write_review': 'അഭിപ്രായം എഴുതുക',
      'contact_whatsapp': 'വാട്ട്‌സ്ആപ്പിൽ ബന്ധപ്പെടുക',
      'no_recent_study': 'നിങ്ങളുടെ പുരോഗതി കാണാൻ ഒരു കോഴ്സ് തുടങ്ങുക',
      'start_learning': 'പഠനം തുടങ്ങുക',
      'all_categories': 'എല്ലാ വിഭാഗങ്ങളും',
      'explore_courses': 'ഞങ്ങളുടെ കോഴ്സുകൾ പര്യവേക്ഷണം ചെയ്യുക',
      'notification': 'അറിയിപ്പ്',
      'privacy': 'സ്വകാര്യത',
      'purchased': 'വാങ്ങിയവ',
      'achieved': 'നേടിയവ',
      'certificates': 'സർട്ടിഫിക്കറ്റുകൾ',
      'about_desc':
          'സർക്കാർ പരീക്ഷകൾക്കായുള്ള ഇന്ത്യയിലെ പ്രമുഖ പഠന പ്ലാറ്റ്‌ഫോം.',
      'whatsapp_title': 'കമ്മ്യൂണിറ്റിയിൽ ചേരുക',
      'my_courses': 'എന്റെ കോഴ്സുകൾ',
      'leaderboard': 'ലീഡർബോർഡ്',
      'mock_tests': 'മോക്ക് ടെസ്റ്റുകൾ',
      'continue_learning': 'പഠനം തുടരുക',
      'practice_improve': 'പരിശീലിക്കുകയും മെച്ചപ്പെടുത്തുകയും ചെയ്യുക',
      'compete_achieve': 'മത്സരിക്കുകയും നേടുകയും ചെയ്യുക',
      'welcome_msg': 'സ്കൈ ഹൈയിലേക്ക് സ്വാഗതം',
      'login_track': 'പുരോഗതി അറിയാൻ ലോഗിൻ ചെയ്യുക',
      'hi': 'ഹായ്',
      'continue_journey': 'നിങ്ങളുടെ പഠന യാത്ര തുടരുക!',
      'identity_required': 'തിരിച്ചറിയൽ ആവശ്യമാണ്',
      'signin_sync':
          'നിങ്ങളുടെ പുരോഗതി സമന്വയിപ്പിക്കാനും പ്രീമിയം സർട്ടിഫിക്കറ്റുകൾ നേടാനും കമ്മ്യൂണിറ്റിയിൽ ചേരാനും സൈൻ ഇൻ ചെയ്യുക.',
      'signin_now': 'ഇപ്പോൾ സൈൻ ഇൻ ചെയ്യുക',
      'logout_confirm': 'നിങ്ങൾക്ക് പുറത്തുകടക്കണമെന്ന് ഉറപ്പാണോ?',
      'close': 'അടയ്ക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'email': 'ഇമെയിൽ',
      'call': 'വിളിക്കുക',
      'address': 'വിലാസം',
      'whatsapp_community': 'വാട്ട്‌സ്ആപ്പ് കമ്മ്യൂണിറ്റിയിൽ ചേരുക',
      'connect_aspirants': '50,000+ ഉദ്യോഗാർത്ഥികളുമായി ബന്ധപ്പെടുക',
      'happy_students': 'ഞങ്ങളുടെ സന്തോഷവാനായ വിദ്യാർത്ഥികൾ',
      'what_students_say': 'വിദ്യാർത്ഥികൾക്ക് പറയാനുള്ളത്',
      'login_required': 'ലോഗിൻ ആവശ്യമാണ്',
      'signin_payment':
          'പേയ്‌മെന്റുമായി മുന്നോട്ട് പോകാൻ ദയവായി സൈൻ ഇൻ ചെയ്യുക.',
      'search_categories': 'വിഭാഗങ്ങൾ തിരയുക...',
      'no_categories_found': 'വിഭാഗങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
      'try_searching_else': 'മറ്റെന്തെങ്കിലും തിരയാൻ ശ്രമിക്കുക',
      'explore_exam_categories':
          'സർക്കാർ പരീക്ഷാ വിഭാഗങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക',
      'find_category_prep':
          'നിങ്ങളുടെ പരീക്ഷാ തയ്യാറെടുപ്പിന് അനുയോജ്യമായ വിഭാഗം കണ്ടെത്തുക',
      'no_materials_available': 'മെറ്റീരിയലുകൾ ലഭ്യമല്ല',
      'no_companies_available': 'കമ്പനികൾ ലഭ്യമല്ല',
      'check_back_later': 'പുതിയ ഉള്ളടക്കത്തിനായി പിന്നീട് പരിശോധിക്കുക.',
      'cant_find_looking': 'നിങ്ങൾ തിരയുന്നത് കണ്ടെത്താൻ കഴിയുന്നില്ലേ?',
      'help_find_category':
          'ശരിയായ വിഭാഗം കണ്ടെത്താൻ ഞങ്ങളെ സഹായിക്കാൻ അനുവദിക്കൂ.',
      'contact_us': 'ഞങ്ങളെ ബന്ധപ്പെടുക',
      'organization': 'സ്ഥാപനം',
      'item': 'ഇനം',
      'companies': 'കമ്പനികൾ',
      'search_books_notes': 'പുസ്തകങ്ങൾ, കുറിപ്പുകൾ തിരയുക...',
      'continue_learning_sub': 'പഠനം\nതുടരുക',
      'notes_pdfs_sub': 'കുറിപ്പുകൾ, PDFകൾ\nകൂടുതൽ',
      'module_prefix': 'ഭാഗം',
      'content_locked_upgrade':
          'ഈ ഉള്ളടക്കം ലോക്ക് ചെയ്തിരിക്കുന്നു. അൺലോക്ക് ചെയ്യാൻ അപ്‌ഗ്രേഡ് ചെയ്യുക.',
      'premium_content': 'പ്രീമിയം ഉള്ളടക്കം',
      'premium_module_desc':
          'ഈ മോഡ്യൂൾ ഞങ്ങളുടെ എലൈറ്റ് ലേണിംഗ് പാത്തിന്റെ ഭാഗമാണ്. എല്ലാ മോഡ്യൂളുകളും അഡ്വാൻസ്ഡ് ടെസ്റ്റ് സീരീസുകളും അൺലോക്ക് ചെയ്യുന്നതിന് നിങ്ങളുടെ സബ്‌സ്‌ക്രിപ്‌ഷൻ അപ്‌ഗ്രേഡ് ചെയ്യുക.',
      'maybe_later': 'പിന്നീടാകാം',
      'upgrade_now': 'ഇപ്പോൾ അപ്‌ഗ്രേഡ് ചെയ്യുക',
      'login_module_desc':
          'പ്രീമിയം മോഡ്യൂളുകൾ ആക്സസ് ചെയ്യുന്നതിനും നിങ്ങളുടെ പുരോഗതി ട്രാക്ക് ചെയ്യുന്നതിനും ദയവായി ലോഗിൻ ചെയ്യുക.',
      'login_now': 'ഇപ്പോൾ ലോഗിൻ ചെയ്യുക',
      'no_courses_available': 'കോഴ്സുകൾ ലഭ്യമല്ല',
      'check_back_later_courses':
          'നിലവിൽ നിങ്ങളുടെ മുൻഗണനകൾക്കായി കോഴ്സുകളൊന്നും ലഭ്യമല്ല. ദയവായി പിന്നീട് വീണ്ടും പരിശോധിക്കുക!',
      'got_it': 'ശരി',
      'failed_load_materials': 'സാമഗ്രികൾ ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു',
      'no_matching_found': 'അനുയോജ്യമായ സാമഗ്രികളൊന്നും കണ്ടെത്തിയില്ല',
      'video_player_coming_soon': 'വീഡിയോ പ്ലെയർ ഉടൻ വരും!',
      'failed_load_jobs': 'ജോലികൾ ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു',
      'resume_course': 'കോഴ്സ് പുനരാരംഭിക്കുക',
      'company_default_desc':
          'ഇന്ത്യയിലുടനീളം 7,000+ സ്റ്റേഷനുകളെ ബന്ധിപ്പിക്കുന്ന ലോകത്തിലെ ഏറ്റവും വലിയ റെയിൽവേ ശൃംഖലകളിലൊന്ന് - ദേശീയ അടിസ്ഥാന സൗകര്യങ്ങളുടെയും പൊതു സേവന മികവിന്റെയും നെടുംതൂൺ.',
      'no_files_available_desc':
          'ഈ സമയത്ത് ഈ വിഭാഗത്തിനായി ഫയലുകളൊന്നും ലഭ്യമല്ല. അവ ഉടൻ നിങ്ങളിലേക്ക് എത്തിക്കാൻ ഞങ്ങൾ കഠിനമായി പരിശ്രമിക്കുന്നു!',
      'no_rankings_yet': 'റാങ്കിംഗുകൾ ലഭ്യമല്ല!',
      'leaderboard_empty_desc':
          'ലീഡർബോർഡ് ഇപ്പോൾ ശൂന്യമാണ്.\nപഠനം ആരംഭിക്കുക, ഇവിടെ എത്തുന്ന ആദ്യത്തെ ആളാകൂ!',
      'climb_leaderboard': 'ലീഡർബോർഡിൽ കയറുക',
      'study_learn_title': 'പഠിക്കുക',
      'study_learn_desc':
          'മൊഡ്യൂളുകൾ പൂർത്തിയാക്കി നിങ്ങളുടെ അറിവ് വികസിപ്പിക്കുക',
      'take_tests_title': 'പരീക്ഷകൾ എഴുതുക',
      'take_tests_desc': 'പരീക്ഷകൾ എഴുതി നിങ്ങളുടെ സ്കോർ മെച്ചപ്പെടുത്തുക',
      'earn_points_title': 'പോയിന്റുകൾ നേടുക',
      'earn_points_desc': 'ഉയർന്ന സ്കോർ നേടി റാങ്ക് മെച്ചപ്പെടുത്തുക',
      'consistency_today': 'ഇന്ന് സ്ഥിരത പുലർത്തുക,',
      'lead_tomorrow': 'നാളെ ലീഡർബോർഡിനെ നയിക്കുക!',
      'tagline': 'നക്ഷത്രങ്ങളെ ലക്ഷ്യം വയ്ക്കുക',
      'skip': 'ഒഴിവാക്കുക',
      'get_started': 'ആരംഭിക്കുക',
      'next_step': 'അടുത്ത പടി',
      'onboarding_title_1': 'വിജയം കൈവരിക്കാൻ\nഎളുപ്പമാണ്',
      'onboarding_desc_1':
          'മികവിനായി രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്ന ഞങ്ങളുടെ വ്യക്തിഗതമാക്കിയ ലേണിംഗ് ഇക്കോസിസ്റ്റം ഉപയോഗിച്ച് നിങ്ങളുടെ കഴിവുകൾ അൺലോക്ക് ചെയ്യുക.',
      'onboarding_highlight_1': 'മികച്ച രീതിയിൽ പഠിക്കുക',
      'onboarding_title_2': 'പരീക്ഷകളിൽ\nമികവ് പുലർത്തുക',
      'onboarding_desc_2':
          'മോക്ക് ടെസ്റ്റുകളുടെയും തത്സമയ പ്രകടന വിശകലനത്തിന്റെയും വിപുലമായ ലൈബ്രറിയിലേക്ക് കടക്കുക.',
      'onboarding_highlight_2': 'എല്ലാ പരീക്ഷയിലും മികവ്',
      'onboarding_title_3': 'ക്രമീകരിച്ച\nപഠന പാതകൾ',
      'onboarding_desc_3':
          'നിങ്ങളുടെ പ്രത്യേക അക്കാദമിക് ആവശ്യങ്ങൾക്കനുസരിച്ചുള്ള കാറ്റഗറി അടിസ്ഥാനമാക്കിയുള്ള പഠന മൊഡ്യൂളുകൾ പര്യവേക്ഷണം ചെയ്യുക.',
      'onboarding_highlight_3': 'കാറ്റഗറി അടിസ്ഥാനമാക്കിയുള്ള പഠനം',
      'no_active_notifications': 'സജീവമായ അറിയിപ്പുകളൊന്നുമില്ല',

      'access_premium_journey':
          'നിങ്ങളുടെ പ്രീമിയം ലേണിംഗ് യാത്ര ആക്സസ് ചെയ്യുക',
      'otp_login': 'OTP ലോഗിൻ',
      'password_tab': 'പാസ്‌വേഡ്',
      'email_address': 'ഇമെയിൽ വിലാസം',
      'otp_hint': '6-അക്ക OTP കോഡ്',
      'resend_otp_in': 'OTP വീണ്ടും അയയ്ക്കുക',
      'resend_otp': 'OTP വീണ്ടും അയയ്ക്കുക',
      'password_hint': 'പാസ്‌വേഡ്',
      'activate_session': 'സെഷൻ സജീവമാക്കുക',
      'get_otp_code': 'OTP കോഡ് നേടുക',
      'sign_in': 'സൈൻ ഇൻ',
      'dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ? ',
      'create_profile': 'പ്രൊഫൈൽ സൃഷ്ടിക്കുക',
      'enter_email': 'ദയവായി നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
      'enter_password': 'ദയവായി നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
      'otp_sent_success': 'നിങ്ങളുടെ ഇമെയിലിലേക്ക് OTP അയച്ചു',
      'otp_send_failed':
          'OTP അയയ്ക്കുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി നിങ്ങളുടെ ഇമെയിൽ പരിശോധിക്കുക.',
      'enter_otp': 'ദയവായി OTP നൽകുക',
      'invalid_otp_failed': 'അസാധുവായ OTP അല്ലെങ്കിൽ ലോഗിൻ പരാജയപ്പെട്ടു',
      'invalid_credentials': 'അസാധുവായ ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ്',
      'about_exam': 'പരീക്ഷയെക്കുറിച്ച്',
      'syllabus_overview': 'സിലബസ് അവലോകനം',
      'target_year': 'ലക്ഷ്യ വർഷം',
      'duration': 'കാലയളവ്',
      'questions': 'ചോദ്യങ്ങൾ',
      'rating': 'റേറ്റിംഗ്',
      'start_preparation': 'തയ്യാറെടുപ്പ് ആരംഭിക്കുക',
      'submit_test_title': 'പരീക്ഷ സമർപ്പിക്കണോ?',
      'submit_test_desc': 'നിങ്ങളുടെ പരീക്ഷ സമർപ്പിക്കണമെന്ന് ഉറപ്പാണോ?',
      'unanswered_questions_warning':
          'നിങ്ങൾക്ക് {count} ഉത്തരമില്ലാത്ത ചോദ്യങ്ങളുണ്ട്.',
      'review_more': 'കൂടുതൽ അവലോകനം ചെയ്യുക',
      'submit_now': 'ഇപ്പോൾ സമർപ്പിക്കുക',
      'quit_test_title': 'പരീക്ഷ ഉപേക്ഷിക്കണോ?',
      'quit_test_desc':
          'നിങ്ങൾക്ക് പുറത്തുകടക്കണമെന്ന് ഉറപ്പാണോ? നിങ്ങളുടെ നിലവിലെ പരീക്ഷാ പുരോഗതി നഷ്ടപ്പെടും.',
      'stay': 'തുടരുക',
      'exit': 'പുറത്തുകടക്കുക',
      'back_to_learning': 'തിരികെ പഠനത്തിലേക്ക്',
      'no_questions_found': 'ചോദ്യങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
      'no_questions_desc':
          'ഈ പരീക്ഷാ സെറ്റിനായി ഇപ്പോൾ ചോദ്യങ്ങളൊന്നും കണ്ടെത്തിയില്ല. ദയവായി പിന്നീട് വീണ്ടും പരിശോധിക്കുക.',
      'go_back': 'പിന്നിലേക്ക് പോകുക',
      'test_instructions': 'പരീക്ഷാ നിർദ്ദേശങ്ങൾ',
      'submitting_test': 'നിങ്ങളുടെ പരീക്ഷ സമർപ്പിക്കുന്നു...',
      'important_rules': 'പ്രധാന നിയമങ്ങൾ',
      'rule_1': 'ഓരോ ചോദ്യത്തിനും 1 മാർക്ക് വീതമുണ്ട്.',
      'rule_2': 'ആകെ സമയം {min} മിനിറ്റാണ്.',
      'rule_3': 'സമയം കഴിയുമ്പോൾ പരീക്ഷ സ്വയം സമർപ്പിക്കപ്പെടും.',
      'rule_4': 'ചോദ്യങ്ങൾ ഇംഗ്ലീഷിൽ ലഭ്യമാണ്.',
      'start_test_now': 'ഇപ്പോൾ പരീക്ഷ ആരംഭിക്കുക',
      'minutes': 'മിനിറ്റുകൾ',
      'easy': 'എളുപ്പം',
      'medium': 'മിതമായി',
      'hard': 'കഠിനം',
      'progress': 'പുരോഗതി',
      'continue_lesson': 'പാഠം തുടരുക',
      'explore_gov_exams':
          'മികച്ച സർക്കാർ പരീക്ഷാ വിഭാഗങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക',
      'no_courses_right_now': 'ഇപ്പോൾ കോഴ്സുകളൊന്നും ലഭ്യമല്ല',
      'available_materials': 'ലഭ്യമായ സാമഗ്രികൾ',
      'items_count': '{count} എണ്ണം',
      'mod_prefix': 'MOD',
      'no_test_series': 'ടെസ്റ്റ് സീരീസുകളൊന്നും ഇതുവരെ ലഭ്യമല്ല.',
      'no_sets_available': 'ഈ മൊഡ്യൂളിനായി സെറ്റുകളൊന്നും ഇതുവരെ ലഭ്യമല്ല.',
      'module_integrated_soon':
          'ഈ മൊഡ്യൂൾ ഇപ്പോൾ സംയോജിപ്പിക്കുന്നു.\nദയവായി ഉടൻ വീണ്ടും പരിശോധിക്കുക.',
      'learning_journey': 'പഠന യാത്ര',
      'modules': 'മൊഡ്യൂളുകൾ',
      'your_progress': 'നിങ്ങളുടെ പുരോഗതി',
      'keep_learning_great': 'പഠനം തുടരുക! നിങ്ങൾ നന്നായി ചെയ്യുന്നു.',
      'all_modules_completed': 'ഈ കോഴ്സിലെ എല്ലാ മൊഡ്യൂളുകളും പൂർത്തിയായി!',
      'finish_journey': 'യാത്ര പൂർത്തിയാക്കുക',
      'complete_next_module': 'പൂർത്തിയാക്കുക & അടുത്ത മൊഡ്യൂൾ',
      'exit_confirm_title': 'യാത്രയിൽ നിന്ന് പുറത്തുകടക്കണോ?',
      'exit_confirm_desc':
          'നിങ്ങൾക്ക് പുറത്തുകടക്കണമെന്ന് ഉറപ്പാണോ? ഈ സെഷനിലെ നിങ്ങളുടെ പുരോഗതി സംരക്ഷിക്കപ്പെടും.',
      'dismiss_all': 'എല്ലാം ഒഴിവാക്കുക',
      'instruction_guide_title': 'ദ്രുത നിർദ്ദേശ ഗൈഡ്',
      'instruction_guide_desc':
          'സൈഡ് മെനുവിൽ നിന്ന് നിങ്ങളുടെ എല്ലാ പഠന മൊഡ്യൂളുകളും മോക്ക് ടെസ്റ്റുകളും വീഡിയോ പാഠങ്ങളും ആക്സസ് ചെയ്യുക.',
      'instruction_step_1': 'മൊഡ്യൂളുകൾ മാറ്റാൻ മെനു ഐക്കണിൽ ടാപ്പ് ചെയ്യുക',
      'instruction_step_2':
          'ഓരോ വിഭാഗത്തിലും നിങ്ങളുടെ പുരോഗതി ട്രാക്ക് ചെയ്യുക',
      'got_it_lets_go': 'മനസ്സിലായി, പോകാം!',
      'keep_learning_btn': 'പഠനം തുടരുക',
      'yes_exit': 'അതെ, പുറത്തുകടക്കുക',
      'no_internet': 'കണക്ഷൻ ഇല്ല',
      'connect_internet': 'ഇന്റർനെറ്റ് ബന്ധിപ്പിക്കുക',
      'connect_internet_desc':
          'ദയവായി നിങ്ങളുടെ ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
      'try_again': 'വീണ്ടും ശ്രമിക്കുക',
      'checking_connection': 'പരിശോധിക്കുന്നു...',
    },
    'Kannada': {
      'free_study_materials': 'ಉಚಿತ ಅಧ್ಯಯನ ಸಾಮಗ್ರಿಗಳು',
      'search_hint': 'ಕೋರ್ಸ್‌ಗಳು, ಪರೀಕ್ಷೆಗಳನ್ನು ಹುಡುಕಿ...',
      'categories': 'ವರ್ಗಗಳು',
      'continue_studying': 'ಓದುವುದನ್ನು ಮುಂದುವರಿಸಿ',
      'free_exams': 'ಉಚಿತ ಪರೀಕ್ಷೆಗಳು',
      'study_materials': 'ಅಧ್ಯಯನ ಸಾಮಗ್ರಿಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'login': 'ಲಾಗಿನ್',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'logout': 'ಲೋಗ್ ಔಟ್',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
      'premium_status': 'ಪ್ರೀಮಿಯಂ ಸ್ಥಿತಿ',
      'about_us': 'ನಮ್ಮ ಬಗ್ಗೆ',
      'write_review': 'ವಿಮರ್ಶೆ ಬರೆಯಿರಿ',
      'contact_whatsapp': 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ',
      'no_recent_study': 'ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ನೋಡಲು ಕೋರ್ಸ್ ಪ್ರಾರಂಭಿಸಿ',
      'start_learning': 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ',
      'all_categories': 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
      'explore_courses': 'ನಮ್ಮ ಕೋರ್ಸ್‌ಗಳ ಶ್ರೇಣಿಯನ್ನು ಅನ್ವೇಷಿಸಿ',
      'notification': 'ಅಧಿಸೂಚನೆ',
      'privacy': 'ಗೌಪ್ಯತೆ',
      'purchased': 'ಖರೀದಿಸಲಾಗಿದೆ',
      'achieved': 'ಸಾಧಿಸಲಾಗಿದೆ',
      'certificates': 'ಪ್ರಮಾಣಪತ್ರಗಳು',
      'about_desc': 'ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆಗಳಿಗಾಗಿ ಭಾರತದ ಪ್ರಮುಖ ಕಲಿಕಾ ವೇದಿಕೆ.',
      'whatsapp_title': 'ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
      'my_courses': 'ನನ್ನ ಕೋರ್ಸ್‌ಗಳು',
      'leaderboard': 'ಲೀಡರ್‌ಬೋರ್ಡ್',
      'mock_tests': 'ಮಾಕ್ ಟೆಸ್ಟ್‌ಗಳು',
      'continue_learning': 'ಕಲಿಯುವುದನ್ನು ಮುಂದುವರಿಸಿ',
      'practice_improve': 'ಅಭ್ಯಾಸ ಮಾಡಿ ಮತ್ತು ಸುಧಾರಿಸಿ',
      'compete_achieve': 'ಸ್ಪರ್ಧಿಸಿ ಮತ್ತು ಸಾಧಿಸಿ',
      'welcome_msg': 'ಸ್ಕೈ ಹೈಗೆ ಸ್ವಾಗತ',
      'login_track': 'ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ',
      'hi': 'ನಮಸ್ಕಾರ',
      'continue_journey': 'ನಿಮ್ಮ ಕಲಿಕೆಯ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಿ!',
      'identity_required': 'ಗುರುತಿನ ಅಗತ್ಯವಿದೆ',
      'signin_sync':
          'ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಸಿಂಕ್ ಮಾಡಲು, ಪ್ರೀಮಿಯಂ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಪಡೆಯಲು ಮತ್ತು ಗಣ್ಯ ಸಮುದಾಯಕ್ಕೆ ಸೇರಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
      'signin_now': 'ಈಗಲೇ ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'logout_confirm': 'ನೀವು ನಿಜವಾಗಿಯೂ ಹೊರಬರಲು ಬಯಸುವಿರಾ?',
      'close': 'ಮುಚ್ಚು',
      'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
      'email': 'ಇಮೇಲ್',
      'call': 'ಕರೆ',
      'address': 'ವಿಳಾಸ',
      'whatsapp_community': 'ವಾಟ್ಸಾಪ್ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
      'connect_aspirants': '50,000+ ಆಕಾಂಕ್ಷಿಗಳೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
      'happy_students': 'ನಮ್ಮ ಸಂತೋಷದ ವಿದ್ಯಾರ್ಥಿಗಳು',
      'what_students_say': 'ನಮ್ಮ ವಿದ್ಯಾರ್ಥಿಗಳು ಏನು ಹೇಳುತ್ತಾರೆ',
      'login_required': 'ಲಾಗಿನ್ ಅಗತ್ಯವಿದೆ',
      'signin_payment': 'ಪಾವತಿಯನ್ನು ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
      'search_categories': 'ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...',
      'no_categories_found': 'ಯಾವುದೇ ವರ್ಗಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'try_searching_else': 'ಬೇರೆ ಏನನ್ನಾದರೂ ಹುಡುಕಲು ಪ್ರಯತ್ನಿಸಿ',
      'explore_exam_categories': 'ಸರ್ಕಾರಿ ಪರೀಕ್ಷಾ ವರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
      'find_category_prep': 'ನಿಮ್ಮ ಪರೀಕ್ಷೆಯ ತಯಾರಿಗಾಗಿ ಸರಿಯಾದ ವರ್ಗವನ್ನು ಹುಡುಕಿ',
      'no_materials_available': 'ಯಾವುದೇ ಸಾಮಗ್ರಿಗಳು ಲಭ್ಯವಿಲ್ಲ',
      'no_companies_available': 'ಯಾವುದೇ ಕಂಪನಿಗಳು ಲಭ್ಯವಿಲ್ಲ',
      'check_back_later': 'ಹೊಸ ವಿಷಯಕ್ಕಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ.',
      'cant_find_looking': 'ನೀವು ಹುಡುಕುತ್ತಿರುವುದು ಸಿಗುತ್ತಿಲ್ಲವೇ?',
      'help_find_category':
          'ಸರಿಯಾದ ವರ್ಗವನ್ನು ಹುಡುಕಲು ನಮಗೆ ಸಹಾಯ ಮಾಡಲು ಅನುಮತಿಸಿ.',
      'contact_us': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      'organization': 'ಸಂಸ್ಥೆ',
      'item': 'ಅಂಶ',
      'companies': 'ಕಂಪನಿಗಳು',
      'search_books_notes': 'ಪುಸ್ತಕಗಳು, ಟಿಪ್ಪಣಿಗಳನ್ನು ಹುಡುಕಿ...',
      'continue_learning_sub': 'ಕಲಿಕೆಯನ್ನು\nಮುಂದುವರಿಸಿ',
      'notes_pdfs_sub': 'ಟಿಪ್ಪಣಿಗಳು, PDFಗಳು\nಮತ್ತು ಇನ್ನಷ್ಟು',
      'module_prefix': 'ಭಾಗ',
      'content_locked_upgrade':
          'ಈ ವಿಷಯವನ್ನು ಲಾಕ್ ಮಾಡಲಾಗಿದೆ. ಅನ್ಲಾಕ್ ಮಾಡಲು ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ.',
      'premium_content': 'ಪ್ರೀಮಿಯಂ ವಿಷಯ',
      'premium_module_desc':
          'ಈ ಮಾಡ್ಯೂಲ್ ನಮ್ಮ ಎಲೈಟ್ ಲರ್ನಿಂಗ್ ಪಾತ್‌ನ ಭಾಗವಾಗಿದೆ. ಎಲ್ಲಾ ಮಾಡ್ಯೂಲ್‌ಗಳು ಮತ್ತು ಸುಧಾರಿತ ಪರೀಕ್ಷಾ ಸರಣಿಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಚಂದಾದಾರಿಕೆಯನ್ನು ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ.',
      'maybe_later': 'ನಂತರ ನೋಡೋಣ',
      'upgrade_now': 'ಈಗಲೇ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ',
      'login_module_desc':
          'ಪ್ರೀಮಿಯಂ ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಮತ್ತು ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.',
      'login_now': 'ಈಗಲೇ ಲಾಗಿನ್ ಮಾಡಿ',
      'no_courses_available': 'ಕೋರ್ಸ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ',
      'check_back_later_courses':
          'ಪ್ರಸ್ತುತ ನಿಮ್ಮ ಆದ್ಯತೆಗಳಿಗಾಗಿ ಯಾವುದೇ ಕೋರ್ಸ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ!',
      'got_it': 'ಸರಿ',
      'failed_load_materials': 'ಸಾಮಗ್ರಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
      'no_matching_found': 'ಯಾವುದೇ ಸಾಮಗ್ರಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'video_player_coming_soon': 'ವಿಡಿಯೋ ಪ್ಲೇಯರ್ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!',
      'failed_load_jobs': 'ಉದ್ಯೋಗಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
      'resume_course': 'ಕೋರ್ಸ್ ಪುನರಾರಂಭಿಸಿ',
      'company_default_desc':
          'ಭಾರತದಾದ್ಯಂತ 7,000+ ನಿಲ್ದಾಣಗಳನ್ನು ಸಂಪರ್ಕಿಸುವ ವಿಶ್ವದ ಅತಿದೊಡ್ಡ ರೈಲ್ವೆ ಜಾಲಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ - ರಾಷ್ಟ್ರೀಯ ಮೂಲಸೌಕರ್ಯ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸೇವಾ ಶ್ರೇಷ್ಠತೆಯ ಸ್ತಂಭ.',
      'no_files_available_desc':
          'ಈ ಸಮಯದಲ್ಲಿ ಈ ವಿಭಾಗಕ್ಕೆ ಯಾವುದೇ ಫೈಲ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ. ಅವುಗಳನ್ನು ಶೀಘ್ರದಲ್ಲೇ ನಿಮಗೆ ತರಲು ನಾವು ಶ್ರಮಿಸುತ್ತಿದ್ದೇವೆ!',
      'no_rankings_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಶ್ರೇಯಾಂಕಗಳಿಲ್ಲ!',
      'leaderboard_empty_desc':
          'ಲೀಡರ್‌ಬೋರ್ಡ್ ಸದ್ಯಕ್ಕೆ ಖಾಲಿಯಿದೆ.\nಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ಇಲ್ಲಿ ಸ್ಥಾನ ಪಡೆಯುವ ಮೊದಲ ವ್ಯಕ್ತಿಯಾಗಿ!',
      'climb_leaderboard': 'ಲೀಡರ್‌ಬೋರ್ಡ್ ಏರಿ',
      'study_learn_title': 'ಓದಿ ಮತ್ತು ಕಲಿಯಿರಿ',
      'study_learn_desc':
          'ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಜ್ಞಾನವನ್ನು ಹೆಚ್ಚಿಸಿಕೊಳ್ಳಿ',
      'take_tests_title': 'ಪರೀಕ್ಷೆಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ',
      'take_tests_desc': 'ಪರೀಕ್ಷೆಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಸ್ಕೋರ್ ಸುಧಾರಿಸಿ',
      'earn_points_title': 'ಅಂಕಗಳನ್ನು ಗಳಿಸಿ',
      'earn_points_desc': 'ಹೆಚ್ಚಿನ ಅಂಕ ಗಳಿಸಿ ಮತ್ತು ಶ್ರೇಯಾಂಕ ಏರಿ',
      'consistency_today': 'ಇಂದು ಸ್ಥಿರವಾಗಿರಿ,',
      'lead_tomorrow': 'ನಾಳೆ ಲೀಡರ್‌ಬೋರ್ಡ್ ಮುನ್ನಡೆಸಿ!',
      'tagline': 'ನಕ್ಷತ್ರಗಳನ್ನು ತಲುಪಿ',
      'skip': 'ಬಿಟ್ಟುಬಿಡಿ',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'next_step': 'ಮುಂದಿನ ಹಂತ',
      'onboarding_title_1': 'ಯಶಸ್ಸು ಸಾಧಿಸುವುದು\nಸುಲಭ',
      'onboarding_desc_1':
          'ಶ್ರೇಷ್ಠತೆಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ನಮ್ಮ ವೈಯಕ್ತೀಕರಿಸಿದ ಕಲಿಕಾ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯೊಂದಿಗೆ ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯವನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಿ.',
      'onboarding_highlight_1': 'ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಕಲಿಯಿರಿ',
      'onboarding_title_2': 'ಪರೀಕ್ಷೆಗಳಲ್ಲಿ\nಪರಿಣತಿ ಪಡೆಯಿರಿ',
      'onboarding_desc_2':
          'ಮಾಕ್ ಟೆಸ್ಟ್‌ಗಳು ಮತ್ತು ನೈಜ-ಸಮಯದ ಕಾರ್ಯಕ್ಷಮತೆಯ ವಿಶ್ಲೇಷಣೆಯ ವಿಶಾಲ ಸಂಗ್ರಹಕ್ಕೆ ಧುಮುಕಿ.',
      'onboarding_highlight_2': 'ಪ್ರತಿ ಪರೀಕ್ಷೆಯಲ್ಲೂ ಶ್ರೇಷ್ಠತೆ',
      'onboarding_title_3': 'ಸಂಘಟಿತ\nಕಲಿಕೆಯ ಮಾರ್ಗಗಳು',
      'onboarding_desc_3':
          'ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಶೈಕ್ಷಣಿಕ ಅಗತ್ಯಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ವರ್ಗ-ಆಧಾರಿತ ಅಧ್ಯಯನ ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.',
      'onboarding_highlight_3': 'ವರ್ಗ ಆಧಾರಿತ ಅಧ್ಯಯನ',
      'no_active_notifications': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',

      'access_premium_journey': 'ನಿಮ್ಮ ಪ್ರೀಮಿಯಂ ಕಲಿಕಾ ಪ್ರಯಾಣವನ್ನು ಪ್ರವೇಶಿಸಿ',
      'otp_login': 'OTP ಲಾಗಿನ್',
      'password_tab': 'ಪಾಸ್‌ವರ್ಡ್',
      'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'otp_hint': '6-ಅಂಕಿಯ OTP ಕೋಡ್',
      'resend_otp_in': 'OTP ಮರುಕಳುಹಿಸಿ',
      'resend_otp': 'OTP ಮರುಕಳುಹಿಸಿ',
      'password_hint': 'ಪಾಸ್‌ವರ್ಡ್',
      'activate_session': 'ಸೆಷನ್ ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'get_otp_code': 'OTP ಕೋಡ್ ಪಡೆಯಿರಿ',
      'sign_in': 'ಸೈನ್ ಇನ್',
      'dont_have_account': 'ಖಾತೆ ಇಲ್ಲವೇ? ',
      'create_profile': 'ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
      'enter_email': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
      'enter_password': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
      'otp_sent_success': 'ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ',
      'otp_send_failed':
          'OTP ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.',
      'enter_otp': 'ದಯವಿಟ್ಟು OTP ನಮೂದಿಸಿ',
      'invalid_otp_failed': 'ಅಮಾನ್ಯ OTP ಅಥವಾ ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
      'invalid_credentials': 'ಅಮಾನ್ಯ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್',
      'about_exam': 'ಪರೀಕ್ಷೆಯ ಬಗ್ಗೆ',
      'syllabus_overview': 'ಪಠ್ಯಕ್ರಮದ ಅವಲೋಕನ',
      'target_year': 'ಗುರಿ ವರ್ಷ',
      'duration': 'ಅವಧಿ',
      'questions': 'ಪ್ರಶ್ನೆಗಳು',
      'rating': 'ರೇಟಿಂಗ್',
      'start_preparation': 'ಸಿದ್ಧತೆ ಪ್ರಾರಂಭಿಸಿ',
      'submit_test_title': 'ಟೆಸ್ಟ್ ಸಲ್ಲಿಸಬೇಕೆ?',
      'submit_test_desc': 'ನಿಮ್ಮ ಟೆಸ್ಟ್ ಅನ್ನು ಸಲ್ಲಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?',
      'unanswered_questions_warning':
          'ನಿಮ್ಮಲ್ಲಿ {count} ಉತ್ತರಿಸದ ಪ್ರಶ್ನೆಗಳಿವೆ.',
      'review_more': 'ಇನ್ನಷ್ಟು ಪರಿಶೀಲಿಸಿ',
      'submit_now': 'ಈಗಲೇ ಸಲ್ಲಿಸಿ',
      'quit_test_title': 'ಟೆಸ್ಟ್ ಬಿಡಬೇಕೆ?',
      'quit_test_desc':
          'ನೀವು ಖಚಿತವಾಗಿ ಹೊರಹೋಗಲು ಬಯಸುವಿರಾ? ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಟೆಸ್ಟ್ ಪ್ರಗತಿ ಕಳೆದುಹೋಗುತ್ತದೆ.',
      'stay': 'ಇರಿ',
      'exit': 'ಹೊರಹೋಗಿ',
      'back_to_learning': 'ಕಲಿಕೆಗೆ ಹಿಂತಿರುಗಿ',
      'no_questions_found': 'ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'no_questions_desc':
          'ಈ ಟೆಸ್ಟ್ ಸೆಟ್‌ಗಾಗಿ ಈ ಸಮಯದಲ್ಲಿ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.',
      'go_back': 'ಹಿಂದಕ್ಕೆ ಹೋಗಿ',
      'test_instructions': 'ಟೆಸ್ಟ್ ಸೂಚನೆಗಳು',
      'submitting_test': 'ನಿಮ್ಮ ಟೆಸ್ಟ್ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
      'important_rules': 'ಪ್ರಮುಖ ನಿಯಮಗಳು',
      'rule_1': 'ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ 1 ಅಂಕವಿರುತ್ತದೆ.',
      'rule_2': 'ಒಟ್ಟು ಅವಧಿ {min} ನಿಮಿಷಗಳು.',
      'rule_3': 'ಸಮಯ ಮುಗಿದಾಗ ಟೆಸ್ಟ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಲ್ಲಿಕೆಯಾಗುತ್ತದೆ.',
      'rule_4': 'ಪ್ರಶ್ನೆಗಳು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಲಭ್ಯವಿವೆ.',
      'start_test_now': 'ಈಗಲೇ ಟೆಸ್ಟ್ ಪ್ರಾರಂಭಿಸಿ',
      'minutes': 'ನಿಮಿಷಗಳು',
      'easy': 'ಸುಲಭ',
      'medium': 'ಮಧ್ಯಮ',
      'hard': 'ಕಠಿಣ',
      'progress': 'ಪ್ರಗತಿ',
      'continue_lesson': 'ಪಾಠವನ್ನು ಮುಂದುವರಿಸಿ',
      'explore_gov_exams': 'ಉನ್ನತ ಸರ್ಕಾರಿ ಪರೀಕ್ಷಾ ವರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
      'no_courses_right_now': 'ಈಗ ಯಾವುದೇ ಕೋರ್ಸ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ',
      'available_materials': 'ಲಭ್ಯವಿರುವ ಸಾಮಗ್ರಿಗಳು',
      'items_count': '{count} ಅಂಶಗಳು',
      'mod_prefix': 'MOD',
      'no_test_series': 'ಇನ್ನೂ ಯಾವುದೇ ಟೆಸ್ಟ್ ಸರಣಿಗಳು ಲಭ್ಯವಿಲ್ಲ.',
      'no_sets_available': 'ಈ ಮಾಡ್ಯೂಲ್‌ಗಾಗಿ ಇನ್ನೂ ಯಾವುದೇ ಸೆಟ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ.',
      'module_integrated_soon':
          'ಈ ಮಾಡ್ಯೂಲ್ ಪ್ರಸ್ತುತ ಸಂಯೋಜಿಸಲ್ಪಡುತ್ತಿದೆ.\nದಯವಿಟ್ಟು ಶೀಘ್ರದಲ್ಲೇ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.',
      'learning_journey': 'ಕಲಿಕೆಯ ಪ್ರಯಾಣ',
      'modules': 'ಮಾಡ್ಯೂಲ್‌ಗಳು',
      'your_progress': 'ನಿಮ್ಮ ಪ್ರಗತಿ',
      'keep_learning_great': 'ಕಲಿಯುತ್ತಿರಿ! ನೀವು ಉತ್ತಮವಾಗಿ ಮಾಡುತ್ತಿದ್ದೀರಿ.',
      'all_modules_completed': 'ಈ ಕೋರ್ಸ್‌ನ ಎಲ್ಲಾ ಮಾಡ್ಯೂಲ್‌ಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ!',
      'finish_journey': 'ಪ್ರಯಾಣವನ್ನು ಮುಗಿಸಿ',
      'complete_next_module': 'ಪೂರ್ಣಗೊಳಿಸಿ ಮತ್ತು ಮುಂದಿನ ಮಾಡ್ಯೂಲ್',
      'exit_confirm_title': 'ಪ್ರಯಾಣದಿಂದ ಹೊರಹೋಗಬೇಕೆ?',
      'exit_confirm_desc':
          'ನೀವು ಖಚಿತವಾಗಿ ಹೊರಹೋಗಲು ಬಯಸುವಿರಾ? ಈ ಸೆಶನ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಉಳಿಸಲಾಗುತ್ತದೆ.',
      'dismiss_all': 'ಎಲ್ಲವನ್ನೂ ವಜಾಗೊಳಿಸಿ',
      'instruction_guide_title': 'ತ್ವರಿತ ಸೂಚನಾ ಮಾರ್ಗದರ್ಶಿ',
      'instruction_guide_desc':
          'ಸೈಡ್ ಮೆನುವಿನಿಂದ ನಿಮ್ಮ ಎಲ್ಲಾ ಅಧ್ಯಯನ ಮಾಡ್ಯೂಲ್‌ಗಳು, ಮಾಕ್ ಟೆಸ್ಟ್‌ಗಳು ಮತ್ತು ವಿಡಿಯೋ ಪಾಠಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.',
      'instruction_step_1': 'ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ಬದಲಾಯಿಸಲು ಮೆನು ಐಕಾನ್ ಟ್ಯಾಪ್ ಮಾಡಿ',
      'instruction_step_2': 'ಪ್ರತಿ ವಿಭಾಗದಲ್ಲಿ ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'got_it_lets_go': 'ಸರಿ, ಹೋಗೋಣ!',
      'keep_learning_btn': 'ಕಲಿಯುತ್ತಿರಿ',
      'yes_exit': 'ಹೌದು, ನಿರ್ಗಮಿಸಿ',
      'no_internet': 'ಸಂಪರ್ಕವಿಲ್ಲ',
      'connect_internet': 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕಿಸಿ',
      'connect_internet_desc':
          'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'checking_connection': 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    },
  };

  String tr(String key) {
    final language = _storage.getSelectedLanguage();
    return _translations[language]?[key] ??
        _translations['English']?[key] ??
        key;
  }
}
