// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU27ASh_0xZmf393jWkzIkDjtCbYMxs3M',
    appId: '1:199387392756:web:04327cea286a4d568b0ca1',
    messagingSenderId: '199387392756',
    projectId: 'sky-high-5de8b',
    authDomain: 'sky-high-5de8b.firebaseapp.com',
    storageBucket: 'sky-high-5de8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSkU3z_hiPfVSUJ7bvAKRWxUk1I5Md_0',
    appId: '1:199387392756:android:6e268976821d529a8b0ca1',
    messagingSenderId: '199387392756',
    projectId: 'sky-high-5de8b',
    storageBucket: 'sky-high-5de8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6Im1NkwkYDIUxFxCX6c8Q7yLQBKJmqU',
    appId: '1:199387392756:ios:f0f8d398af77fca68b0ca1',
    messagingSenderId: '199387392756',
    projectId: 'sky-high-5de8b',
    storageBucket: 'sky-high-5de8b.firebasestorage.app',
    iosBundleId: 'com.example.skyHigh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6Im1NkwkYDIUxFxCX6c8Q7yLQBKJmqU',
    appId: '1:199387392756:ios:f0f8d398af77fca68b0ca1',
    messagingSenderId: '199387392756',
    projectId: 'sky-high-5de8b',
    storageBucket: 'sky-high-5de8b.firebasestorage.app',
    iosBundleId: 'com.example.skyHigh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU27ASh_0xZmf393jWkzIkDjtCbYMxs3M',
    appId: '1:199387392756:web:cbd69332819327048b0ca1',
    messagingSenderId: '199387392756',
    projectId: 'sky-high-5de8b',
    authDomain: 'sky-high-5de8b.firebaseapp.com',
    storageBucket: 'sky-high-5de8b.firebasestorage.app',
  );
}
